'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
'
Namespace wsPeriodos
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PeriodosWSSoap", [Namespace]:="http://tempuri.org/Credito/Periodos")>  _
    Partial Public Class PeriodosWS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetPeriodosVigentesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSaldoPeriodoByAsociadoPeriodoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LoadOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        ''' 
        Public strURL As String
        Public Sub New()
            MyBase.New()
            'Me.Url = Global.DportenisPro.DPTienda.ApplicationUnits.PeriodosUI.My.MySettings.Default.PeriodosUI_wsPeriodos_PeriodosWS
            strURL = "credito/PeriodosDPWS.asmx"
            Dim urlSetting As String = System.Configuration.ConfigurationManager.AppSettings("PeriodosUI.wsPeriodos.PeriodosWS")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://dpssvr/credito/PeriodosDPWS.asmx"
            End If
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetPeriodosVigentesCompleted As GetPeriodosVigentesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSaldoPeriodoByAsociadoPeriodoCompleted As GetSaldoPeriodoByAsociadoPeriodoCompletedEventHandler
        
        '''<remarks/>
        Public Event LoadCompleted As LoadCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/Periodos/GetPeriodosVigentes", RequestNamespace:="http://tempuri.org/Credito/Periodos", ResponseNamespace:="http://tempuri.org/Credito/Periodos", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPeriodosVigentes() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetPeriodosVigentes", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetPeriodosVigentes(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetPeriodosVigentes", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetPeriodosVigentes(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPeriodosVigentesAsync()
            Me.GetPeriodosVigentesAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPeriodosVigentesAsync(ByVal userState As Object)
            If (Me.GetPeriodosVigentesOperationCompleted Is Nothing) Then
                Me.GetPeriodosVigentesOperationCompleted = AddressOf Me.OnGetPeriodosVigentesOperationCompleted
            End If
            Me.InvokeAsync("GetPeriodosVigentes", New Object(-1) {}, Me.GetPeriodosVigentesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPeriodosVigentesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPeriodosVigentesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPeriodosVigentesCompleted(Me, New GetPeriodosVigentesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/Periodos/GetSaldoPeriodoByAsociadoPeriodo", RequestNamespace:="http://tempuri.org/Credito/Periodos", ResponseNamespace:="http://tempuri.org/Credito/Periodos", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSaldoPeriodoByAsociadoPeriodo(ByVal AsociadoID As Integer, ByVal NumPeriodo As Integer) As Double
            Dim results() As Object = Me.Invoke("GetSaldoPeriodoByAsociadoPeriodo", New Object() {AsociadoID, NumPeriodo})
            Return CType(results(0),Double)
        End Function
        
        '''<remarks/>
        Public Function BeginGetSaldoPeriodoByAsociadoPeriodo(ByVal AsociadoID As Integer, ByVal NumPeriodo As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetSaldoPeriodoByAsociadoPeriodo", New Object() {AsociadoID, NumPeriodo}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetSaldoPeriodoByAsociadoPeriodo(ByVal asyncResult As System.IAsyncResult) As Double
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Double)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSaldoPeriodoByAsociadoPeriodoAsync(ByVal AsociadoID As Integer, ByVal NumPeriodo As Integer)
            Me.GetSaldoPeriodoByAsociadoPeriodoAsync(AsociadoID, NumPeriodo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSaldoPeriodoByAsociadoPeriodoAsync(ByVal AsociadoID As Integer, ByVal NumPeriodo As Integer, ByVal userState As Object)
            If (Me.GetSaldoPeriodoByAsociadoPeriodoOperationCompleted Is Nothing) Then
                Me.GetSaldoPeriodoByAsociadoPeriodoOperationCompleted = AddressOf Me.OnGetSaldoPeriodoByAsociadoPeriodoOperationCompleted
            End If
            Me.InvokeAsync("GetSaldoPeriodoByAsociadoPeriodo", New Object() {AsociadoID, NumPeriodo}, Me.GetSaldoPeriodoByAsociadoPeriodoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSaldoPeriodoByAsociadoPeriodoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSaldoPeriodoByAsociadoPeriodoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSaldoPeriodoByAsociadoPeriodoCompleted(Me, New GetSaldoPeriodoByAsociadoPeriodoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/Periodos/Load", RequestNamespace:="http://tempuri.org/Credito/Periodos", ResponseNamespace:="http://tempuri.org/Credito/Periodos", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Load(ByVal ID As Integer) As PeriodoInfo
            Dim results() As Object = Me.Invoke("Load", New Object() {ID})
            Return CType(results(0),PeriodoInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginLoad(ByVal ID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Load", New Object() {ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndLoad(ByVal asyncResult As System.IAsyncResult) As PeriodoInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),PeriodoInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LoadAsync(ByVal ID As Integer)
            Me.LoadAsync(ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LoadAsync(ByVal ID As Integer, ByVal userState As Object)
            If (Me.LoadOperationCompleted Is Nothing) Then
                Me.LoadOperationCompleted = AddressOf Me.OnLoadOperationCompleted
            End If
            Me.InvokeAsync("Load", New Object() {ID}, Me.LoadOperationCompleted, userState)
        End Sub
        
        Private Sub OnLoadOperationCompleted(ByVal arg As Object)
            If (Not (Me.LoadCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LoadCompleted(Me, New LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/Credito/Periodos")>  _
    Partial Public Class PeriodoInfo
        
        Private statusRegistroField As Boolean
        
        Private fechaField As Date
        
        Private usuarioField As String
        
        Private porcLimPagoD5Field As Integer
        
        Private porcLimPagoD4Field As Integer
        
        Private porcLimPagoD3Field As Integer
        
        Private porcLimPagoD2Field As Integer
        
        Private porcLimPagoD1Field As Integer
        
        Private diasCorteField As Integer
        
        Private diaPago2Field As Date
        
        Private diaPago1Field As Date
        
        Private fechaCorte2Field As Integer
        
        Private fechaCorte1Field As Integer
        
        Private numDiasPeriodoField As Integer
        
        Private annoField As Integer
        
        Private periodoIDField As Integer
        
        Private numPeriodosField As Integer
        
        '''<comentarios/>
        Public Property StatusRegistro() As Boolean
            Get
                Return Me.statusRegistroField
            End Get
            Set
                Me.statusRegistroField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PorcLimPagoD5() As Integer
            Get
                Return Me.porcLimPagoD5Field
            End Get
            Set
                Me.porcLimPagoD5Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PorcLimPagoD4() As Integer
            Get
                Return Me.porcLimPagoD4Field
            End Get
            Set
                Me.porcLimPagoD4Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PorcLimPagoD3() As Integer
            Get
                Return Me.porcLimPagoD3Field
            End Get
            Set
                Me.porcLimPagoD3Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PorcLimPagoD2() As Integer
            Get
                Return Me.porcLimPagoD2Field
            End Get
            Set
                Me.porcLimPagoD2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PorcLimPagoD1() As Integer
            Get
                Return Me.porcLimPagoD1Field
            End Get
            Set
                Me.porcLimPagoD1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property DiasCorte() As Integer
            Get
                Return Me.diasCorteField
            End Get
            Set
                Me.diasCorteField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property DiaPago2() As Date
            Get
                Return Me.diaPago2Field
            End Get
            Set
                Me.diaPago2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property DiaPago1() As Date
            Get
                Return Me.diaPago1Field
            End Get
            Set
                Me.diaPago1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaCorte2() As Integer
            Get
                Return Me.fechaCorte2Field
            End Get
            Set
                Me.fechaCorte2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaCorte1() As Integer
            Get
                Return Me.fechaCorte1Field
            End Get
            Set
                Me.fechaCorte1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property NumDiasPeriodo() As Integer
            Get
                Return Me.numDiasPeriodoField
            End Get
            Set
                Me.numDiasPeriodoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Anno() As Integer
            Get
                Return Me.annoField
            End Get
            Set
                Me.annoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PeriodoID() As Integer
            Get
                Return Me.periodoIDField
            End Get
            Set
                Me.periodoIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property NumPeriodos() As Integer
            Get
                Return Me.numPeriodosField
            End Get
            Set
                Me.numPeriodosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetPeriodosVigentesCompletedEventHandler(ByVal sender As Object, ByVal e As GetPeriodosVigentesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPeriodosVigentesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetSaldoPeriodoByAsociadoPeriodoCompletedEventHandler(ByVal sender As Object, ByVal e As GetSaldoPeriodoByAsociadoPeriodoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSaldoPeriodoByAsociadoPeriodoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Double
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Double)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub LoadCompletedEventHandler(ByVal sender As Object, ByVal e As LoadCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LoadCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PeriodoInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PeriodoInfo)
            End Get
        End Property
    End Class
End Namespace
