'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
'
Namespace wsAbonoDPVale
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Abonos .::. Dportenis ValeSoap", [Namespace]:="http://tempuri.org/Credito/AbonoDPVale")>  _
    Partial Public Class AbonosDportenisVale
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private InsertOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SelectCreditoDPValeAllOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetUltimoAbonoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        ''' 
        Public strURL As String
        Public Sub New()
            MyBase.New
            'Me.Url = Global.DportenisPro.DPTienda.ApplicationUnits.AbonosDPVale.My.MySettings.Default.AbonosDPVale_wsAbonoDPVale_Abonos_x0020___x003A__x003A___x0020_Dportenis_x0020_Vale
            strURL = "credito/AbonoDPVALE.asmx"
            Dim urlSetting As String = System.Configuration.ConfigurationManager.AppSettings("AbonosDPVale.wsAbonoDPVale.Abonos .::. Dportenis Vale")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://dpssvr/credito/AbonoDPVALE.asmx"
            End If
            If (Me.IsLocalFileSystemWebService(Me.Url) = True) Then
                Me.UseDefaultCredentials = True
                Me.useDefaultCredentialsSetExplicitly = False
            Else
                Me.useDefaultCredentialsSetExplicitly = True
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event InsertCompleted As InsertCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCompleted As UpdateCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteCompleted As DeleteCompletedEventHandler
        
        '''<remarks/>
        Public Event SelectCreditoDPValeAllCompleted As SelectCreditoDPValeAllCompletedEventHandler
        
        '''<remarks/>
        Public Event GetUltimoAbonoCompleted As GetUltimoAbonoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/AbonoDPVale/Insert", RequestNamespace:="http://tempuri.org/Credito/AbonoDPVale", ResponseNamespace:="http://tempuri.org/Credito/AbonoDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Insert(ByVal oAbonoDPVale As AbonoDPValeInfo, ByVal Iva As Double) As AbonoDPValeInfo
            Dim results() As Object = Me.Invoke("Insert", New Object() {oAbonoDPVale, Iva})
            Return CType(results(0),AbonoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginInsert(ByVal oAbonoDPVale As AbonoDPValeInfo, ByVal Iva As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Insert", New Object() {oAbonoDPVale, Iva}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndInsert(ByVal asyncResult As System.IAsyncResult) As AbonoDPValeInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AbonoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InsertAsync(ByVal oAbonoDPVale As AbonoDPValeInfo, ByVal Iva As Double)
            Me.InsertAsync(oAbonoDPVale, Iva, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InsertAsync(ByVal oAbonoDPVale As AbonoDPValeInfo, ByVal Iva As Double, ByVal userState As Object)
            If (Me.InsertOperationCompleted Is Nothing) Then
                Me.InsertOperationCompleted = AddressOf Me.OnInsertOperationCompleted
            End If
            Me.InvokeAsync("Insert", New Object() {oAbonoDPVale, Iva}, Me.InsertOperationCompleted, userState)
        End Sub
        
        Private Sub OnInsertOperationCompleted(ByVal arg As Object)
            If (Not (Me.InsertCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InsertCompleted(Me, New InsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/AbonoDPVale/Update", RequestNamespace:="http://tempuri.org/Credito/AbonoDPVale", ResponseNamespace:="http://tempuri.org/Credito/AbonoDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Update(ByVal oAbonoDPVale As AbonoDPValeInfo) As AbonoDPValeInfo
            Dim results() As Object = Me.Invoke("Update", New Object() {oAbonoDPVale})
            Return CType(results(0),AbonoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginUpdate(ByVal oAbonoDPVale As AbonoDPValeInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Update", New Object() {oAbonoDPVale}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndUpdate(ByVal asyncResult As System.IAsyncResult) As AbonoDPValeInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AbonoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal oAbonoDPVale As AbonoDPValeInfo)
            Me.UpdateAsync(oAbonoDPVale, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal oAbonoDPVale As AbonoDPValeInfo, ByVal userState As Object)
            If (Me.UpdateOperationCompleted Is Nothing) Then
                Me.UpdateOperationCompleted = AddressOf Me.OnUpdateOperationCompleted
            End If
            Me.InvokeAsync("Update", New Object() {oAbonoDPVale}, Me.UpdateOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCompleted(Me, New UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/AbonoDPVale/Delete", RequestNamespace:="http://tempuri.org/Credito/AbonoDPVale", ResponseNamespace:="http://tempuri.org/Credito/AbonoDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Delete(ByVal oAbonoDPVale As AbonoDPValeInfo)
            Me.Invoke("Delete", New Object() {oAbonoDPVale})
        End Sub
        
        '''<remarks/>
        Public Function BeginDelete(ByVal oAbonoDPVale As AbonoDPValeInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Delete", New Object() {oAbonoDPVale}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndDelete(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteAsync(ByVal oAbonoDPVale As AbonoDPValeInfo)
            Me.DeleteAsync(oAbonoDPVale, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteAsync(ByVal oAbonoDPVale As AbonoDPValeInfo, ByVal userState As Object)
            If (Me.DeleteOperationCompleted Is Nothing) Then
                Me.DeleteOperationCompleted = AddressOf Me.OnDeleteOperationCompleted
            End If
            Me.InvokeAsync("Delete", New Object() {oAbonoDPVale}, Me.DeleteOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/AbonoDPVale/SelectCreditoDPValeAll", RequestNamespace:="http://tempuri.org/Credito/AbonoDPVale", ResponseNamespace:="http://tempuri.org/Credito/AbonoDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SelectCreditoDPValeAll(ByVal OnlyEnabledRecords As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SelectCreditoDPValeAll", New Object() {OnlyEnabledRecords})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginSelectCreditoDPValeAll(ByVal OnlyEnabledRecords As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SelectCreditoDPValeAll", New Object() {OnlyEnabledRecords}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSelectCreditoDPValeAll(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SelectCreditoDPValeAllAsync(ByVal OnlyEnabledRecords As Boolean)
            Me.SelectCreditoDPValeAllAsync(OnlyEnabledRecords, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SelectCreditoDPValeAllAsync(ByVal OnlyEnabledRecords As Boolean, ByVal userState As Object)
            If (Me.SelectCreditoDPValeAllOperationCompleted Is Nothing) Then
                Me.SelectCreditoDPValeAllOperationCompleted = AddressOf Me.OnSelectCreditoDPValeAllOperationCompleted
            End If
            Me.InvokeAsync("SelectCreditoDPValeAll", New Object() {OnlyEnabledRecords}, Me.SelectCreditoDPValeAllOperationCompleted, userState)
        End Sub
        
        Private Sub OnSelectCreditoDPValeAllOperationCompleted(ByVal arg As Object)
            If (Not (Me.SelectCreditoDPValeAllCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SelectCreditoDPValeAllCompleted(Me, New SelectCreditoDPValeAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/AbonoDPVale/GetUltimoAbono", RequestNamespace:="http://tempuri.org/Credito/AbonoDPVale", ResponseNamespace:="http://tempuri.org/Credito/AbonoDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUltimoAbono(ByVal CodSegmentoCredito As String, ByVal AsociadoId As Integer) As AbonoDPValeInfo
            Dim results() As Object = Me.Invoke("GetUltimoAbono", New Object() {CodSegmentoCredito, AsociadoId})
            Return CType(results(0),AbonoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginGetUltimoAbono(ByVal CodSegmentoCredito As String, ByVal AsociadoId As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetUltimoAbono", New Object() {CodSegmentoCredito, AsociadoId}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetUltimoAbono(ByVal asyncResult As System.IAsyncResult) As AbonoDPValeInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AbonoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUltimoAbonoAsync(ByVal CodSegmentoCredito As String, ByVal AsociadoId As Integer)
            Me.GetUltimoAbonoAsync(CodSegmentoCredito, AsociadoId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUltimoAbonoAsync(ByVal CodSegmentoCredito As String, ByVal AsociadoId As Integer, ByVal userState As Object)
            If (Me.GetUltimoAbonoOperationCompleted Is Nothing) Then
                Me.GetUltimoAbonoOperationCompleted = AddressOf Me.OnGetUltimoAbonoOperationCompleted
            End If
            Me.InvokeAsync("GetUltimoAbono", New Object() {CodSegmentoCredito, AsociadoId}, Me.GetUltimoAbonoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUltimoAbonoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUltimoAbonoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUltimoAbonoCompleted(Me, New GetUltimoAbonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/Credito/AbonoDPVale")>  _
    Partial Public Class AbonoDPValeInfo
        
        Private iDAbonoField As Integer
        
        Private codAlmacenField As String
        
        Private codCajaField As String
        
        Private iDClienteField As Integer
        
        Private codSegCredField As String
        
        Private codTipAbonoField As Integer
        
        Private saldoAntField As Double
        
        Private pagoMinField As Double
        
        Private montoPagoField As Double
        
        Private saldNuevoField As Double
        
        Private usuarioField As String
        
        Private fechaField As Date
        
        Private statusRegistroField As Boolean
        
        Private detalleField As System.Data.DataSet
        
        Private saldoDPValeField As Decimal
        
        Private asociadoIDField As Integer
        
        Private plazaConsecutivoField As String
        
        Private referenciaField As String
        
        Private bonificacionField As Double
        
        '''<comentarios/>
        Public Property IDAbono() As Integer
            Get
                Return Me.iDAbonoField
            End Get
            Set
                Me.iDAbonoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodAlmacen() As String
            Get
                Return Me.codAlmacenField
            End Get
            Set
                Me.codAlmacenField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodCaja() As String
            Get
                Return Me.codCajaField
            End Get
            Set
                Me.codCajaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IDCliente() As Integer
            Get
                Return Me.iDClienteField
            End Get
            Set
                Me.iDClienteField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodSegCred() As String
            Get
                Return Me.codSegCredField
            End Get
            Set
                Me.codSegCredField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodTipAbono() As Integer
            Get
                Return Me.codTipAbonoField
            End Get
            Set
                Me.codTipAbonoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SaldoAnt() As Double
            Get
                Return Me.saldoAntField
            End Get
            Set
                Me.saldoAntField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PagoMin() As Double
            Get
                Return Me.pagoMinField
            End Get
            Set
                Me.pagoMinField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MontoPago() As Double
            Get
                Return Me.montoPagoField
            End Get
            Set
                Me.montoPagoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SaldNuevo() As Double
            Get
                Return Me.saldNuevoField
            End Get
            Set
                Me.saldNuevoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property StatusRegistro() As Boolean
            Get
                Return Me.statusRegistroField
            End Get
            Set
                Me.statusRegistroField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Detalle() As System.Data.DataSet
            Get
                Return Me.detalleField
            End Get
            Set
                Me.detalleField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SaldoDPVale() As Decimal
            Get
                Return Me.saldoDPValeField
            End Get
            Set
                Me.saldoDPValeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AsociadoID() As Integer
            Get
                Return Me.asociadoIDField
            End Get
            Set
                Me.asociadoIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PlazaConsecutivo() As String
            Get
                Return Me.plazaConsecutivoField
            End Get
            Set
                Me.plazaConsecutivoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Referencia() As String
            Get
                Return Me.referenciaField
            End Get
            Set
                Me.referenciaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Bonificacion() As Double
            Get
                Return Me.bonificacionField
            End Get
            Set
                Me.bonificacionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub InsertCompletedEventHandler(ByVal sender As Object, ByVal e As InsertCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InsertCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AbonoDPValeInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AbonoDPValeInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub UpdateCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AbonoDPValeInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AbonoDPValeInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DeleteCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SelectCreditoDPValeAllCompletedEventHandler(ByVal sender As Object, ByVal e As SelectCreditoDPValeAllCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SelectCreditoDPValeAllCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetUltimoAbonoCompletedEventHandler(ByVal sender As Object, ByVal e As GetUltimoAbonoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUltimoAbonoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AbonoDPValeInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AbonoDPValeInfo)
            End Get
        End Property
    End Class
End Namespace
