'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
'
Namespace wsPagosCreditoDirecto
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PagosCreditoDirectoSoap", [Namespace]:="http://tempuri.org/Credito/PagosCreditoDirecto")>  _
    Partial Public Class PagosCreditoDirecto
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CreatePagoCreditoDirectoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeletePagoCreditoDirectoByFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPagoCreditoDirectoFacturaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPagoCreditoDirectoAsociadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPagoCreditoDirectoAsociadosRangeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        ''' 
        Public strUrl As String
        Public Sub New()
            MyBase.New
            'Me.Url = Global.DportenisPro.DPTienda.ApplicationUnits.FacturasFormaPago.My.MySettings.Default.FacturasFormaPagoAU_wsPagosCreditoDirecto_PagosCreditoDirecto
            strURL = "credito/CreditosEnTienda.asmx"
            Dim urlSetting As String = System.Configuration.ConfigurationManager.AppSettings("FacturasFormaPagoAU.wsCreditosEnTienda.Credito .:::· CreditosEnTienda")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://dpssvr/credito/CreditosEnTienda.asmx"
            End If
            If (Me.IsLocalFileSystemWebService(Me.Url) = True) Then
                Me.UseDefaultCredentials = True
                Me.useDefaultCredentialsSetExplicitly = False
            Else
                Me.useDefaultCredentialsSetExplicitly = True
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CreatePagoCreditoDirectoCompleted As CreatePagoCreditoDirectoCompletedEventHandler
        
        '''<remarks/>
        Public Event DeletePagoCreditoDirectoByFacturaCompleted As DeletePagoCreditoDirectoByFacturaCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPagoCreditoDirectoFacturaCompleted As GetPagoCreditoDirectoFacturaCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPagoCreditoDirectoAsociadoCompleted As GetPagoCreditoDirectoAsociadoCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPagoCreditoDirectoAsociadosRangeCompleted As GetPagoCreditoDirectoAsociadosRangeCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/PagosCreditoDirecto/CreatePagoCreditoDirecto", RequestNamespace:="http://tempuri.org/Credito/PagosCreditoDirecto", ResponseNamespace:="http://tempuri.org/Credito/PagosCreditoDirecto", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreatePagoCreditoDirecto(ByVal Data As PagosCreditoDirectoInfo) As Integer
            Dim results() As Object = Me.Invoke("CreatePagoCreditoDirecto", New Object() {Data})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginCreatePagoCreditoDirecto(ByVal Data As PagosCreditoDirectoInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreatePagoCreditoDirecto", New Object() {Data}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCreatePagoCreditoDirecto(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreatePagoCreditoDirectoAsync(ByVal Data As PagosCreditoDirectoInfo)
            Me.CreatePagoCreditoDirectoAsync(Data, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreatePagoCreditoDirectoAsync(ByVal Data As PagosCreditoDirectoInfo, ByVal userState As Object)
            If (Me.CreatePagoCreditoDirectoOperationCompleted Is Nothing) Then
                Me.CreatePagoCreditoDirectoOperationCompleted = AddressOf Me.OnCreatePagoCreditoDirectoOperationCompleted
            End If
            Me.InvokeAsync("CreatePagoCreditoDirecto", New Object() {Data}, Me.CreatePagoCreditoDirectoOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreatePagoCreditoDirectoOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreatePagoCreditoDirectoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreatePagoCreditoDirectoCompleted(Me, New CreatePagoCreditoDirectoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/PagosCreditoDirecto/DeletePagoCreditoDirectoByFactura", RequestNamespace:="http://tempuri.org/Credito/PagosCreditoDirecto", ResponseNamespace:="http://tempuri.org/Credito/PagosCreditoDirecto", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub DeletePagoCreditoDirectoByFactura(ByVal ClienteId As Integer, ByVal CodigoCaja As String, ByVal CodigoAlmacen As String, ByVal FolioFactura As Integer)
            Me.Invoke("DeletePagoCreditoDirectoByFactura", New Object() {ClienteId, CodigoCaja, CodigoAlmacen, FolioFactura})
        End Sub
        
        '''<remarks/>
        Public Function BeginDeletePagoCreditoDirectoByFactura(ByVal ClienteId As Integer, ByVal CodigoCaja As String, ByVal CodigoAlmacen As String, ByVal FolioFactura As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DeletePagoCreditoDirectoByFactura", New Object() {ClienteId, CodigoCaja, CodigoAlmacen, FolioFactura}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndDeletePagoCreditoDirectoByFactura(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeletePagoCreditoDirectoByFacturaAsync(ByVal ClienteId As Integer, ByVal CodigoCaja As String, ByVal CodigoAlmacen As String, ByVal FolioFactura As Integer)
            Me.DeletePagoCreditoDirectoByFacturaAsync(ClienteId, CodigoCaja, CodigoAlmacen, FolioFactura, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeletePagoCreditoDirectoByFacturaAsync(ByVal ClienteId As Integer, ByVal CodigoCaja As String, ByVal CodigoAlmacen As String, ByVal FolioFactura As Integer, ByVal userState As Object)
            If (Me.DeletePagoCreditoDirectoByFacturaOperationCompleted Is Nothing) Then
                Me.DeletePagoCreditoDirectoByFacturaOperationCompleted = AddressOf Me.OnDeletePagoCreditoDirectoByFacturaOperationCompleted
            End If
            Me.InvokeAsync("DeletePagoCreditoDirectoByFactura", New Object() {ClienteId, CodigoCaja, CodigoAlmacen, FolioFactura}, Me.DeletePagoCreditoDirectoByFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeletePagoCreditoDirectoByFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeletePagoCreditoDirectoByFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeletePagoCreditoDirectoByFacturaCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/PagosCreditoDirecto/GetPagoCreditoDirectoFactura", RequestNamespace:="http://tempuri.org/Credito/PagosCreditoDirecto", ResponseNamespace:="http://tempuri.org/Credito/PagosCreditoDirecto", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPagoCreditoDirectoFactura(ByVal AsociadoID As Integer, ByVal CodAlmacen As String, ByVal CodCaja As String, ByVal FolioFactura As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetPagoCreditoDirectoFactura", New Object() {AsociadoID, CodAlmacen, CodCaja, FolioFactura})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetPagoCreditoDirectoFactura(ByVal AsociadoID As Integer, ByVal CodAlmacen As String, ByVal CodCaja As String, ByVal FolioFactura As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetPagoCreditoDirectoFactura", New Object() {AsociadoID, CodAlmacen, CodCaja, FolioFactura}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetPagoCreditoDirectoFactura(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPagoCreditoDirectoFacturaAsync(ByVal AsociadoID As Integer, ByVal CodAlmacen As String, ByVal CodCaja As String, ByVal FolioFactura As Integer)
            Me.GetPagoCreditoDirectoFacturaAsync(AsociadoID, CodAlmacen, CodCaja, FolioFactura, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPagoCreditoDirectoFacturaAsync(ByVal AsociadoID As Integer, ByVal CodAlmacen As String, ByVal CodCaja As String, ByVal FolioFactura As Integer, ByVal userState As Object)
            If (Me.GetPagoCreditoDirectoFacturaOperationCompleted Is Nothing) Then
                Me.GetPagoCreditoDirectoFacturaOperationCompleted = AddressOf Me.OnGetPagoCreditoDirectoFacturaOperationCompleted
            End If
            Me.InvokeAsync("GetPagoCreditoDirectoFactura", New Object() {AsociadoID, CodAlmacen, CodCaja, FolioFactura}, Me.GetPagoCreditoDirectoFacturaOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPagoCreditoDirectoFacturaOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPagoCreditoDirectoFacturaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPagoCreditoDirectoFacturaCompleted(Me, New GetPagoCreditoDirectoFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/PagosCreditoDirecto/GetPagoCreditoDirectoAsociado", RequestNamespace:="http://tempuri.org/Credito/PagosCreditoDirecto", ResponseNamespace:="http://tempuri.org/Credito/PagosCreditoDirecto", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPagoCreditoDirectoAsociado(ByVal CodAlmacen As String, ByVal AsociadoID As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetPagoCreditoDirectoAsociado", New Object() {CodAlmacen, AsociadoID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetPagoCreditoDirectoAsociado(ByVal CodAlmacen As String, ByVal AsociadoID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetPagoCreditoDirectoAsociado", New Object() {CodAlmacen, AsociadoID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetPagoCreditoDirectoAsociado(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPagoCreditoDirectoAsociadoAsync(ByVal CodAlmacen As String, ByVal AsociadoID As Integer)
            Me.GetPagoCreditoDirectoAsociadoAsync(CodAlmacen, AsociadoID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPagoCreditoDirectoAsociadoAsync(ByVal CodAlmacen As String, ByVal AsociadoID As Integer, ByVal userState As Object)
            If (Me.GetPagoCreditoDirectoAsociadoOperationCompleted Is Nothing) Then
                Me.GetPagoCreditoDirectoAsociadoOperationCompleted = AddressOf Me.OnGetPagoCreditoDirectoAsociadoOperationCompleted
            End If
            Me.InvokeAsync("GetPagoCreditoDirectoAsociado", New Object() {CodAlmacen, AsociadoID}, Me.GetPagoCreditoDirectoAsociadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPagoCreditoDirectoAsociadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPagoCreditoDirectoAsociadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPagoCreditoDirectoAsociadoCompleted(Me, New GetPagoCreditoDirectoAsociadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/PagosCreditoDirecto/GetPagoCreditoDirectoAsociadosRang"& _ 
            "e", RequestNamespace:="http://tempuri.org/Credito/PagosCreditoDirecto", ResponseNamespace:="http://tempuri.org/Credito/PagosCreditoDirecto", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPagoCreditoDirectoAsociadosRange(ByVal AsociadoInicio As Integer, ByVal AsociadoFin As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetPagoCreditoDirectoAsociadosRange", New Object() {AsociadoInicio, AsociadoFin})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetPagoCreditoDirectoAsociadosRange(ByVal AsociadoInicio As Integer, ByVal AsociadoFin As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetPagoCreditoDirectoAsociadosRange", New Object() {AsociadoInicio, AsociadoFin}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetPagoCreditoDirectoAsociadosRange(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPagoCreditoDirectoAsociadosRangeAsync(ByVal AsociadoInicio As Integer, ByVal AsociadoFin As Integer)
            Me.GetPagoCreditoDirectoAsociadosRangeAsync(AsociadoInicio, AsociadoFin, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPagoCreditoDirectoAsociadosRangeAsync(ByVal AsociadoInicio As Integer, ByVal AsociadoFin As Integer, ByVal userState As Object)
            If (Me.GetPagoCreditoDirectoAsociadosRangeOperationCompleted Is Nothing) Then
                Me.GetPagoCreditoDirectoAsociadosRangeOperationCompleted = AddressOf Me.OnGetPagoCreditoDirectoAsociadosRangeOperationCompleted
            End If
            Me.InvokeAsync("GetPagoCreditoDirectoAsociadosRange", New Object() {AsociadoInicio, AsociadoFin}, Me.GetPagoCreditoDirectoAsociadosRangeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPagoCreditoDirectoAsociadosRangeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPagoCreditoDirectoAsociadosRangeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPagoCreditoDirectoAsociadosRangeCompleted(Me, New GetPagoCreditoDirectoAsociadosRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/Credito/PagosCreditoDirecto")>  _
    Partial Public Class PagosCreditoDirectoInfo
        
        Private creditoEnTiendaIDField As Integer
        
        Private asociadoIDField As Integer
        
        Private clienteIDField As Integer
        
        Private codAlmacenField As String
        
        Private codCajaField As String
        
        Private folioFacturaField As Integer
        
        Private fechaFacturaField As Date
        
        Private relacionAbonosField As String
        
        Private fechaLimitePagoField As Date
        
        Private pagoEstablecidoField As Decimal
        
        Private saldoField As Decimal
        
        Private saldoAnteriorField As Decimal
        
        Private saldoVencidoField As Decimal
        
        Private descuentoProntoPagoField As Decimal
        
        Private recargoMorosoField As String
        
        Private usuarioField As String
        
        Private fechaField As Date
        
        Private playerField As String
        
        '''<comentarios/>
        Public Property CreditoEnTiendaID() As Integer
            Get
                Return Me.creditoEnTiendaIDField
            End Get
            Set
                Me.creditoEnTiendaIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AsociadoID() As Integer
            Get
                Return Me.asociadoIDField
            End Get
            Set
                Me.asociadoIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ClienteID() As Integer
            Get
                Return Me.clienteIDField
            End Get
            Set
                Me.clienteIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodAlmacen() As String
            Get
                Return Me.codAlmacenField
            End Get
            Set
                Me.codAlmacenField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodCaja() As String
            Get
                Return Me.codCajaField
            End Get
            Set
                Me.codCajaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FolioFactura() As Integer
            Get
                Return Me.folioFacturaField
            End Get
            Set
                Me.folioFacturaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaFactura() As Date
            Get
                Return Me.fechaFacturaField
            End Get
            Set
                Me.fechaFacturaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RelacionAbonos() As String
            Get
                Return Me.relacionAbonosField
            End Get
            Set
                Me.relacionAbonosField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaLimitePago() As Date
            Get
                Return Me.fechaLimitePagoField
            End Get
            Set
                Me.fechaLimitePagoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PagoEstablecido() As Decimal
            Get
                Return Me.pagoEstablecidoField
            End Get
            Set
                Me.pagoEstablecidoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Saldo() As Decimal
            Get
                Return Me.saldoField
            End Get
            Set
                Me.saldoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SaldoAnterior() As Decimal
            Get
                Return Me.saldoAnteriorField
            End Get
            Set
                Me.saldoAnteriorField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SaldoVencido() As Decimal
            Get
                Return Me.saldoVencidoField
            End Get
            Set
                Me.saldoVencidoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property DescuentoProntoPago() As Decimal
            Get
                Return Me.descuentoProntoPagoField
            End Get
            Set
                Me.descuentoProntoPagoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RecargoMoroso() As String
            Get
                Return Me.recargoMorosoField
            End Get
            Set
                Me.recargoMorosoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Player() As String
            Get
                Return Me.playerField
            End Get
            Set
                Me.playerField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub CreatePagoCreditoDirectoCompletedEventHandler(ByVal sender As Object, ByVal e As CreatePagoCreditoDirectoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreatePagoCreditoDirectoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DeletePagoCreditoDirectoByFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetPagoCreditoDirectoFacturaCompletedEventHandler(ByVal sender As Object, ByVal e As GetPagoCreditoDirectoFacturaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPagoCreditoDirectoFacturaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetPagoCreditoDirectoAsociadoCompletedEventHandler(ByVal sender As Object, ByVal e As GetPagoCreditoDirectoAsociadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPagoCreditoDirectoAsociadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetPagoCreditoDirectoAsociadosRangeCompletedEventHandler(ByVal sender As Object, ByVal e As GetPagoCreditoDirectoAsociadosRangeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPagoCreditoDirectoAsociadosRangeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
