'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
'
Namespace ws.ValesDescuentoEmpleado
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ValesDescuentoEmpleadoSoap", [Namespace]:="http://tempuri.org/Credito/ValesDescuentoEmpleado")>  _
    Partial Public Class ValesDescuentoEmpleado
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetValeDescuentoEmpleadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InsertValeDescuentoUtilizadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.DportenisPro.DPTienda.ApplicationUnits.CatalogoTipoDescuento.My.MySettings.Default.CatalogoTipoDescuento_ws_ValesDescuentoEmpleado_ValesDescuentoEmpleado
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetValeDescuentoEmpleadoCompleted As GetValeDescuentoEmpleadoCompletedEventHandler
        
        '''<remarks/>
        Public Event InsertValeDescuentoUtilizadoCompleted As InsertValeDescuentoUtilizadoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/ValesDescuentoEmpleado/GetValeDescuentoEmpleado", RequestNamespace:="http://tempuri.org/Credito/ValesDescuentoEmpleado", ResponseNamespace:="http://tempuri.org/Credito/ValesDescuentoEmpleado", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetValeDescuentoEmpleado(ByVal Folio As Integer, ByVal TipoVale As String) As ValesDescuentoEmpleadoInfo
            Dim results() As Object = Me.Invoke("GetValeDescuentoEmpleado", New Object() {Folio, TipoVale})
            Return CType(results(0),ValesDescuentoEmpleadoInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginGetValeDescuentoEmpleado(ByVal Folio As Integer, ByVal TipoVale As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetValeDescuentoEmpleado", New Object() {Folio, TipoVale}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetValeDescuentoEmpleado(ByVal asyncResult As System.IAsyncResult) As ValesDescuentoEmpleadoInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ValesDescuentoEmpleadoInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetValeDescuentoEmpleadoAsync(ByVal Folio As Integer, ByVal TipoVale As String)
            Me.GetValeDescuentoEmpleadoAsync(Folio, TipoVale, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetValeDescuentoEmpleadoAsync(ByVal Folio As Integer, ByVal TipoVale As String, ByVal userState As Object)
            If (Me.GetValeDescuentoEmpleadoOperationCompleted Is Nothing) Then
                Me.GetValeDescuentoEmpleadoOperationCompleted = AddressOf Me.OnGetValeDescuentoEmpleadoOperationCompleted
            End If
            Me.InvokeAsync("GetValeDescuentoEmpleado", New Object() {Folio, TipoVale}, Me.GetValeDescuentoEmpleadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetValeDescuentoEmpleadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetValeDescuentoEmpleadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetValeDescuentoEmpleadoCompleted(Me, New GetValeDescuentoEmpleadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/ValesDescuentoEmpleado/InsertValeDescuentoUtilizado", RequestNamespace:="http://tempuri.org/Credito/ValesDescuentoEmpleado", ResponseNamespace:="http://tempuri.org/Credito/ValesDescuentoEmpleado", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub InsertValeDescuentoUtilizado(ByVal oValeUtilizado As ValesDescuentoEmpleadoInfo)
            Me.Invoke("InsertValeDescuentoUtilizado", New Object() {oValeUtilizado})
        End Sub
        
        '''<remarks/>
        Public Function BeginInsertValeDescuentoUtilizado(ByVal oValeUtilizado As ValesDescuentoEmpleadoInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("InsertValeDescuentoUtilizado", New Object() {oValeUtilizado}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndInsertValeDescuentoUtilizado(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InsertValeDescuentoUtilizadoAsync(ByVal oValeUtilizado As ValesDescuentoEmpleadoInfo)
            Me.InsertValeDescuentoUtilizadoAsync(oValeUtilizado, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InsertValeDescuentoUtilizadoAsync(ByVal oValeUtilizado As ValesDescuentoEmpleadoInfo, ByVal userState As Object)
            If (Me.InsertValeDescuentoUtilizadoOperationCompleted Is Nothing) Then
                Me.InsertValeDescuentoUtilizadoOperationCompleted = AddressOf Me.OnInsertValeDescuentoUtilizadoOperationCompleted
            End If
            Me.InvokeAsync("InsertValeDescuentoUtilizado", New Object() {oValeUtilizado}, Me.InsertValeDescuentoUtilizadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnInsertValeDescuentoUtilizadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.InsertValeDescuentoUtilizadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InsertValeDescuentoUtilizadoCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/Credito/ValesDescuentoEmpleado")>  _
    Partial Public Class ValesDescuentoEmpleadoInfo
        
        Private folioValeField As Integer
        
        Private folioInicialField As String
        
        Private folioFinalField As String
        
        Private tipoValeField As String
        
        Private caducidadField As Date
        
        Private fechaAltaField As Date
        
        Private usuarioField As String
        
        Private enviadoField As Boolean
        
        Private sucursalField As String
        
        Private resultadoField As Integer
        
        '''<comentarios/>
        Public Property FolioVale() As Integer
            Get
                Return Me.folioValeField
            End Get
            Set
                Me.folioValeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FolioInicial() As String
            Get
                Return Me.folioInicialField
            End Get
            Set
                Me.folioInicialField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FolioFinal() As String
            Get
                Return Me.folioFinalField
            End Get
            Set
                Me.folioFinalField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TipoVale() As String
            Get
                Return Me.tipoValeField
            End Get
            Set
                Me.tipoValeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Caducidad() As Date
            Get
                Return Me.caducidadField
            End Get
            Set
                Me.caducidadField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaAlta() As Date
            Get
                Return Me.fechaAltaField
            End Get
            Set
                Me.fechaAltaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Enviado() As Boolean
            Get
                Return Me.enviadoField
            End Get
            Set
                Me.enviadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Sucursal() As String
            Get
                Return Me.sucursalField
            End Get
            Set
                Me.sucursalField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Resultado() As Integer
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetValeDescuentoEmpleadoCompletedEventHandler(ByVal sender As Object, ByVal e As GetValeDescuentoEmpleadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetValeDescuentoEmpleadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ValesDescuentoEmpleadoInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ValesDescuentoEmpleadoInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub InsertValeDescuentoUtilizadoCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
