'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
'
Namespace wsPeriodoDetalle
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PeriodoDetalleWSSoap", [Namespace]:="http://tempuri.org/Credito/PeriodoDetalleWS")>  _
    Partial Public Class PeriodoDetalleWS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SelectByNumPeriodoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LiquidarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private PeriodosNoLiquidadosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReporteCobranzaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SelectPeriodoActualOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        ''' 
        Public strURL As String
        Public Sub New()
            MyBase.New
            'Me.Url = Global.DportenisPro.DPTienda.ApplicationUnits.PeriodoDetalleUI.My.MySettings.Default.PeriodoDetalleUI_wsPeriodoDetalle_PeriodoDetalleWS
            strURL = "credito/periododetallews.asmx"
            Dim urlSetting As String = System.Configuration.ConfigurationManager.AppSettings("PeriodoDetalleUI.wsPeriodoDetalle.PeriodoDetalleWS")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://dpssvr/credito/periododetallews.asmx"
            End If
            If (Me.IsLocalFileSystemWebService(Me.Url) = True) Then
                Me.UseDefaultCredentials = True
                Me.useDefaultCredentialsSetExplicitly = False
            Else
                Me.useDefaultCredentialsSetExplicitly = True
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SelectByNumPeriodoCompleted As SelectByNumPeriodoCompletedEventHandler
        
        '''<remarks/>
        Public Event LiquidarCompleted As LiquidarCompletedEventHandler
        
        '''<remarks/>
        Public Event PeriodosNoLiquidadosCompleted As PeriodosNoLiquidadosCompletedEventHandler
        
        '''<remarks/>
        Public Event ReporteCobranzaCompleted As ReporteCobranzaCompletedEventHandler
        
        '''<remarks/>
        Public Event SelectPeriodoActualCompleted As SelectPeriodoActualCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/PeriodoDetalleWS/SelectByNumPeriodo", RequestNamespace:="http://tempuri.org/Credito/PeriodoDetalleWS", ResponseNamespace:="http://tempuri.org/Credito/PeriodoDetalleWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SelectByNumPeriodo(ByVal NumPeriodo As Integer, ByVal AsociadoID As Integer) As PeriodoDetalleInfo
            Dim results() As Object = Me.Invoke("SelectByNumPeriodo", New Object() {NumPeriodo, AsociadoID})
            Return CType(results(0),PeriodoDetalleInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginSelectByNumPeriodo(ByVal NumPeriodo As Integer, ByVal AsociadoID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SelectByNumPeriodo", New Object() {NumPeriodo, AsociadoID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSelectByNumPeriodo(ByVal asyncResult As System.IAsyncResult) As PeriodoDetalleInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),PeriodoDetalleInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SelectByNumPeriodoAsync(ByVal NumPeriodo As Integer, ByVal AsociadoID As Integer)
            Me.SelectByNumPeriodoAsync(NumPeriodo, AsociadoID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SelectByNumPeriodoAsync(ByVal NumPeriodo As Integer, ByVal AsociadoID As Integer, ByVal userState As Object)
            If (Me.SelectByNumPeriodoOperationCompleted Is Nothing) Then
                Me.SelectByNumPeriodoOperationCompleted = AddressOf Me.OnSelectByNumPeriodoOperationCompleted
            End If
            Me.InvokeAsync("SelectByNumPeriodo", New Object() {NumPeriodo, AsociadoID}, Me.SelectByNumPeriodoOperationCompleted, userState)
        End Sub
        
        Private Sub OnSelectByNumPeriodoOperationCompleted(ByVal arg As Object)
            If (Not (Me.SelectByNumPeriodoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SelectByNumPeriodoCompleted(Me, New SelectByNumPeriodoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/PeriodoDetalleWS/Liquidar", RequestNamespace:="http://tempuri.org/Credito/PeriodoDetalleWS", ResponseNamespace:="http://tempuri.org/Credito/PeriodoDetalleWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Liquidar(ByVal ID As Integer, ByVal Liquidado As Boolean, ByVal PagoMin As Decimal, ByVal AsociadoID As Integer)
            Me.Invoke("Liquidar", New Object() {ID, Liquidado, PagoMin, AsociadoID})
        End Sub
        
        '''<remarks/>
        Public Function BeginLiquidar(ByVal ID As Integer, ByVal Liquidado As Boolean, ByVal PagoMin As Decimal, ByVal AsociadoID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Liquidar", New Object() {ID, Liquidado, PagoMin, AsociadoID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndLiquidar(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LiquidarAsync(ByVal ID As Integer, ByVal Liquidado As Boolean, ByVal PagoMin As Decimal, ByVal AsociadoID As Integer)
            Me.LiquidarAsync(ID, Liquidado, PagoMin, AsociadoID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LiquidarAsync(ByVal ID As Integer, ByVal Liquidado As Boolean, ByVal PagoMin As Decimal, ByVal AsociadoID As Integer, ByVal userState As Object)
            If (Me.LiquidarOperationCompleted Is Nothing) Then
                Me.LiquidarOperationCompleted = AddressOf Me.OnLiquidarOperationCompleted
            End If
            Me.InvokeAsync("Liquidar", New Object() {ID, Liquidado, PagoMin, AsociadoID}, Me.LiquidarOperationCompleted, userState)
        End Sub
        
        Private Sub OnLiquidarOperationCompleted(ByVal arg As Object)
            If (Not (Me.LiquidarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LiquidarCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/PeriodoDetalleWS/PeriodosNoLiquidados", RequestNamespace:="http://tempuri.org/Credito/PeriodoDetalleWS", ResponseNamespace:="http://tempuri.org/Credito/PeriodoDetalleWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PeriodosNoLiquidados(ByVal AsociadoID As Integer, ByVal ClienteID As Integer) As Integer
            Dim results() As Object = Me.Invoke("PeriodosNoLiquidados", New Object() {AsociadoID, ClienteID})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginPeriodosNoLiquidados(ByVal AsociadoID As Integer, ByVal ClienteID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PeriodosNoLiquidados", New Object() {AsociadoID, ClienteID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndPeriodosNoLiquidados(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub PeriodosNoLiquidadosAsync(ByVal AsociadoID As Integer, ByVal ClienteID As Integer)
            Me.PeriodosNoLiquidadosAsync(AsociadoID, ClienteID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub PeriodosNoLiquidadosAsync(ByVal AsociadoID As Integer, ByVal ClienteID As Integer, ByVal userState As Object)
            If (Me.PeriodosNoLiquidadosOperationCompleted Is Nothing) Then
                Me.PeriodosNoLiquidadosOperationCompleted = AddressOf Me.OnPeriodosNoLiquidadosOperationCompleted
            End If
            Me.InvokeAsync("PeriodosNoLiquidados", New Object() {AsociadoID, ClienteID}, Me.PeriodosNoLiquidadosOperationCompleted, userState)
        End Sub
        
        Private Sub OnPeriodosNoLiquidadosOperationCompleted(ByVal arg As Object)
            If (Not (Me.PeriodosNoLiquidadosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent PeriodosNoLiquidadosCompleted(Me, New PeriodosNoLiquidadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/PeriodoDetalleWS/ReporteCobranza", RequestNamespace:="http://tempuri.org/Credito/PeriodoDetalleWS", ResponseNamespace:="http://tempuri.org/Credito/PeriodoDetalleWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReporteCobranza(ByVal NumPeriodo As Integer, ByVal CodPlaza As String, ByVal NumAsociadoDel As Integer, ByVal NumAsociadoAl As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ReporteCobranza", New Object() {NumPeriodo, CodPlaza, NumAsociadoDel, NumAsociadoAl})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginReporteCobranza(ByVal NumPeriodo As Integer, ByVal CodPlaza As String, ByVal NumAsociadoDel As Integer, ByVal NumAsociadoAl As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ReporteCobranza", New Object() {NumPeriodo, CodPlaza, NumAsociadoDel, NumAsociadoAl}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndReporteCobranza(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReporteCobranzaAsync(ByVal NumPeriodo As Integer, ByVal CodPlaza As String, ByVal NumAsociadoDel As Integer, ByVal NumAsociadoAl As Integer)
            Me.ReporteCobranzaAsync(NumPeriodo, CodPlaza, NumAsociadoDel, NumAsociadoAl, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReporteCobranzaAsync(ByVal NumPeriodo As Integer, ByVal CodPlaza As String, ByVal NumAsociadoDel As Integer, ByVal NumAsociadoAl As Integer, ByVal userState As Object)
            If (Me.ReporteCobranzaOperationCompleted Is Nothing) Then
                Me.ReporteCobranzaOperationCompleted = AddressOf Me.OnReporteCobranzaOperationCompleted
            End If
            Me.InvokeAsync("ReporteCobranza", New Object() {NumPeriodo, CodPlaza, NumAsociadoDel, NumAsociadoAl}, Me.ReporteCobranzaOperationCompleted, userState)
        End Sub
        
        Private Sub OnReporteCobranzaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReporteCobranzaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReporteCobranzaCompleted(Me, New ReporteCobranzaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/PeriodoDetalleWS/SelectPeriodoActual", RequestNamespace:="http://tempuri.org/Credito/PeriodoDetalleWS", ResponseNamespace:="http://tempuri.org/Credito/PeriodoDetalleWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SelectPeriodoActual(ByVal Fecha As Date) As Integer
            Dim results() As Object = Me.Invoke("SelectPeriodoActual", New Object() {Fecha})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginSelectPeriodoActual(ByVal Fecha As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SelectPeriodoActual", New Object() {Fecha}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSelectPeriodoActual(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SelectPeriodoActualAsync(ByVal Fecha As Date)
            Me.SelectPeriodoActualAsync(Fecha, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SelectPeriodoActualAsync(ByVal Fecha As Date, ByVal userState As Object)
            If (Me.SelectPeriodoActualOperationCompleted Is Nothing) Then
                Me.SelectPeriodoActualOperationCompleted = AddressOf Me.OnSelectPeriodoActualOperationCompleted
            End If
            Me.InvokeAsync("SelectPeriodoActual", New Object() {Fecha}, Me.SelectPeriodoActualOperationCompleted, userState)
        End Sub
        
        Private Sub OnSelectPeriodoActualOperationCompleted(ByVal arg As Object)
            If (Not (Me.SelectPeriodoActualCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SelectPeriodoActualCompleted(Me, New SelectPeriodoActualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/Credito/PeriodoDetalleWS")>  _
    Partial Public Class PeriodoDetalleInfo
        
        Private statusRegistroField As Boolean
        
        Private fechaField As Date
        
        Private usuarioField As String
        
        Private fechaPagoField As Date
        
        Private fechaFinalField As Date
        
        Private fechaInicialField As Date
        
        Private numPeriodoField As Integer
        
        Private annoField As Integer
        
        Private periodoIDField As Integer
        
        Private periodoDetalleIDField As Integer
        
        Private liquidadoField As Boolean
        
        Private pagoMinimoField As Decimal
        
        '''<comentarios/>
        Public Property StatusRegistro() As Boolean
            Get
                Return Me.statusRegistroField
            End Get
            Set
                Me.statusRegistroField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaPago() As Date
            Get
                Return Me.fechaPagoField
            End Get
            Set
                Me.fechaPagoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaFinal() As Date
            Get
                Return Me.fechaFinalField
            End Get
            Set
                Me.fechaFinalField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaInicial() As Date
            Get
                Return Me.fechaInicialField
            End Get
            Set
                Me.fechaInicialField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property NumPeriodo() As Integer
            Get
                Return Me.numPeriodoField
            End Get
            Set
                Me.numPeriodoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Anno() As Integer
            Get
                Return Me.annoField
            End Get
            Set
                Me.annoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PeriodoID() As Integer
            Get
                Return Me.periodoIDField
            End Get
            Set
                Me.periodoIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PeriodoDetalleID() As Integer
            Get
                Return Me.periodoDetalleIDField
            End Get
            Set
                Me.periodoDetalleIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Liquidado() As Boolean
            Get
                Return Me.liquidadoField
            End Get
            Set
                Me.liquidadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PagoMinimo() As Decimal
            Get
                Return Me.pagoMinimoField
            End Get
            Set
                Me.pagoMinimoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SelectByNumPeriodoCompletedEventHandler(ByVal sender As Object, ByVal e As SelectByNumPeriodoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SelectByNumPeriodoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PeriodoDetalleInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PeriodoDetalleInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub LiquidarCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub PeriodosNoLiquidadosCompletedEventHandler(ByVal sender As Object, ByVal e As PeriodosNoLiquidadosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class PeriodosNoLiquidadosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub ReporteCobranzaCompletedEventHandler(ByVal sender As Object, ByVal e As ReporteCobranzaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReporteCobranzaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SelectPeriodoActualCompletedEventHandler(ByVal sender As Object, ByVal e As SelectPeriodoActualCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SelectPeriodoActualCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
End Namespace
