'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
'
Namespace wsCreditoDPVale
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Credito .:::· CreditosDPValeSoap", [Namespace]:="http://ws.dportenis.com.mx/Credito/CreditosDPVale")>  _
    Partial Public Class CreditoCreditosDPVale
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CreateCreditoDPValeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateCreditoDPValeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateCreditoDPValeSaldoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteCreditoDPValeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCreditoDPValeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetListCreditosDPValeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetListCreditosDPValeByClienteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.DportenisPro.DPTienda.ApplicationUnits.NotasCreditoAU.My.MySettings.Default.NotasCreditoAU_wsCreditoDPVale_Credito_x0020___x003A__x003A__x003A___x0020_CreditosDPVale
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CreateCreditoDPValeCompleted As CreateCreditoDPValeCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCreditoDPValeCompleted As UpdateCreditoDPValeCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCreditoDPValeSaldoCompleted As UpdateCreditoDPValeSaldoCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteCreditoDPValeCompleted As DeleteCreditoDPValeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCreditoDPValeCompleted As GetCreditoDPValeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetListCreditosDPValeCompleted As GetListCreditosDPValeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetListCreditosDPValeByClienteCompleted As GetListCreditosDPValeByClienteCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/CreateCreditoDPVale", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreateCreditoDPVale(ByVal Data As CreditoDPValeInfo) As Integer
            Dim results() As Object = Me.Invoke("CreateCreditoDPVale", New Object() {Data})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginCreateCreditoDPVale(ByVal Data As CreditoDPValeInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreateCreditoDPVale", New Object() {Data}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCreateCreditoDPVale(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreateCreditoDPValeAsync(ByVal Data As CreditoDPValeInfo)
            Me.CreateCreditoDPValeAsync(Data, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateCreditoDPValeAsync(ByVal Data As CreditoDPValeInfo, ByVal userState As Object)
            If (Me.CreateCreditoDPValeOperationCompleted Is Nothing) Then
                Me.CreateCreditoDPValeOperationCompleted = AddressOf Me.OnCreateCreditoDPValeOperationCompleted
            End If
            Me.InvokeAsync("CreateCreditoDPVale", New Object() {Data}, Me.CreateCreditoDPValeOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateCreditoDPValeOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateCreditoDPValeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateCreditoDPValeCompleted(Me, New CreateCreditoDPValeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/UpdateCreditoDPVale", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateCreditoDPVale(ByVal Data As CreditoDPValeInfo)
            Me.Invoke("UpdateCreditoDPVale", New Object() {Data})
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdateCreditoDPVale(ByVal Data As CreditoDPValeInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateCreditoDPVale", New Object() {Data}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdateCreditoDPVale(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCreditoDPValeAsync(ByVal Data As CreditoDPValeInfo)
            Me.UpdateCreditoDPValeAsync(Data, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCreditoDPValeAsync(ByVal Data As CreditoDPValeInfo, ByVal userState As Object)
            If (Me.UpdateCreditoDPValeOperationCompleted Is Nothing) Then
                Me.UpdateCreditoDPValeOperationCompleted = AddressOf Me.OnUpdateCreditoDPValeOperationCompleted
            End If
            Me.InvokeAsync("UpdateCreditoDPVale", New Object() {Data}, Me.UpdateCreditoDPValeOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateCreditoDPValeOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCreditoDPValeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCreditoDPValeCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/UpdateCreditoDPValeSaldo", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateCreditoDPValeSaldo(ByVal AsociadoID As Integer, ByVal Monto As Decimal)
            Me.Invoke("UpdateCreditoDPValeSaldo", New Object() {AsociadoID, Monto})
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdateCreditoDPValeSaldo(ByVal AsociadoID As Integer, ByVal Monto As Decimal, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateCreditoDPValeSaldo", New Object() {AsociadoID, Monto}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdateCreditoDPValeSaldo(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCreditoDPValeSaldoAsync(ByVal AsociadoID As Integer, ByVal Monto As Decimal)
            Me.UpdateCreditoDPValeSaldoAsync(AsociadoID, Monto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCreditoDPValeSaldoAsync(ByVal AsociadoID As Integer, ByVal Monto As Decimal, ByVal userState As Object)
            If (Me.UpdateCreditoDPValeSaldoOperationCompleted Is Nothing) Then
                Me.UpdateCreditoDPValeSaldoOperationCompleted = AddressOf Me.OnUpdateCreditoDPValeSaldoOperationCompleted
            End If
            Me.InvokeAsync("UpdateCreditoDPValeSaldo", New Object() {AsociadoID, Monto}, Me.UpdateCreditoDPValeSaldoOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateCreditoDPValeSaldoOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCreditoDPValeSaldoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCreditoDPValeSaldoCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/DeleteCreditoDPVale", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub DeleteCreditoDPVale(ByVal ID As Integer)
            Me.Invoke("DeleteCreditoDPVale", New Object() {ID})
        End Sub
        
        '''<remarks/>
        Public Function BeginDeleteCreditoDPVale(ByVal ID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DeleteCreditoDPVale", New Object() {ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndDeleteCreditoDPVale(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteCreditoDPValeAsync(ByVal ID As Integer)
            Me.DeleteCreditoDPValeAsync(ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteCreditoDPValeAsync(ByVal ID As Integer, ByVal userState As Object)
            If (Me.DeleteCreditoDPValeOperationCompleted Is Nothing) Then
                Me.DeleteCreditoDPValeOperationCompleted = AddressOf Me.OnDeleteCreditoDPValeOperationCompleted
            End If
            Me.InvokeAsync("DeleteCreditoDPVale", New Object() {ID}, Me.DeleteCreditoDPValeOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteCreditoDPValeOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteCreditoDPValeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteCreditoDPValeCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/GetCreditoDPVale", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCreditoDPVale(ByVal ID As Integer) As CreditoDPValeInfo
            Dim results() As Object = Me.Invoke("GetCreditoDPVale", New Object() {ID})
            Return CType(results(0),CreditoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginGetCreditoDPVale(ByVal ID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetCreditoDPVale", New Object() {ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetCreditoDPVale(ByVal asyncResult As System.IAsyncResult) As CreditoDPValeInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),CreditoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCreditoDPValeAsync(ByVal ID As Integer)
            Me.GetCreditoDPValeAsync(ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCreditoDPValeAsync(ByVal ID As Integer, ByVal userState As Object)
            If (Me.GetCreditoDPValeOperationCompleted Is Nothing) Then
                Me.GetCreditoDPValeOperationCompleted = AddressOf Me.OnGetCreditoDPValeOperationCompleted
            End If
            Me.InvokeAsync("GetCreditoDPVale", New Object() {ID}, Me.GetCreditoDPValeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCreditoDPValeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCreditoDPValeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCreditoDPValeCompleted(Me, New GetCreditoDPValeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/GetListCreditosDPVale", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetListCreditosDPVale(ByVal EnabledRecordsOnly As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetListCreditosDPVale", New Object() {EnabledRecordsOnly})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetListCreditosDPVale(ByVal EnabledRecordsOnly As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetListCreditosDPVale", New Object() {EnabledRecordsOnly}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetListCreditosDPVale(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetListCreditosDPValeAsync(ByVal EnabledRecordsOnly As Boolean)
            Me.GetListCreditosDPValeAsync(EnabledRecordsOnly, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetListCreditosDPValeAsync(ByVal EnabledRecordsOnly As Boolean, ByVal userState As Object)
            If (Me.GetListCreditosDPValeOperationCompleted Is Nothing) Then
                Me.GetListCreditosDPValeOperationCompleted = AddressOf Me.OnGetListCreditosDPValeOperationCompleted
            End If
            Me.InvokeAsync("GetListCreditosDPVale", New Object() {EnabledRecordsOnly}, Me.GetListCreditosDPValeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetListCreditosDPValeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetListCreditosDPValeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetListCreditosDPValeCompleted(Me, New GetListCreditosDPValeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/GetListCreditosDPValeByCliente", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetListCreditosDPValeByCliente(ByVal PlazaID As String, ByVal EnabledRecordsOnly As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetListCreditosDPValeByCliente", New Object() {PlazaID, EnabledRecordsOnly})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetListCreditosDPValeByCliente(ByVal PlazaID As String, ByVal EnabledRecordsOnly As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetListCreditosDPValeByCliente", New Object() {PlazaID, EnabledRecordsOnly}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetListCreditosDPValeByCliente(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetListCreditosDPValeByClienteAsync(ByVal PlazaID As String, ByVal EnabledRecordsOnly As Boolean)
            Me.GetListCreditosDPValeByClienteAsync(PlazaID, EnabledRecordsOnly, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetListCreditosDPValeByClienteAsync(ByVal PlazaID As String, ByVal EnabledRecordsOnly As Boolean, ByVal userState As Object)
            If (Me.GetListCreditosDPValeByClienteOperationCompleted Is Nothing) Then
                Me.GetListCreditosDPValeByClienteOperationCompleted = AddressOf Me.OnGetListCreditosDPValeByClienteOperationCompleted
            End If
            Me.InvokeAsync("GetListCreditosDPValeByCliente", New Object() {PlazaID, EnabledRecordsOnly}, Me.GetListCreditosDPValeByClienteOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetListCreditosDPValeByClienteOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetListCreditosDPValeByClienteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetListCreditosDPValeByClienteCompleted(Me, New GetListCreditosDPValeByClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.dportenis.com.mx/Credito/CreditosDPVale")>  _
    Partial Public Class CreditoDPValeInfo
        
        Private creditoDPValeIDField As Integer
        
        Private asociadoIDField As Integer
        
        Private clienteIDField As Integer
        
        Private bancoField As String
        
        Private limiteCreditoBancarioField As Decimal
        
        Private plazoField As Integer
        
        Private avalNombreField As String
        
        Private avalApellidoPaternoField As String
        
        Private avalApellidoMaternoField As String
        
        Private avalSexoField As String
        
        Private avalDomicilioField As String
        
        Private avalEstadoField As String
        
        Private avalCiudadField As String
        
        Private avalColoniaField As String
        
        Private avalTelefonoField As String
        
        Private avalEmailField As String
        
        Private avalCodigoPostalField As String
        
        Private fechaExpiracionField As Date
        
        Private limiteCreditoField As Decimal
        
        Private saldoField As Decimal
        
        Private saldoVencidoField As Decimal
        
        Private cuentaContableField As String
        
        Private firmaDigitalField() As Byte
        
        Private recordCreatedByField As String
        
        Private recordCreatedOnField As Date
        
        Private recordStatusField As Boolean
        
        Private institucion1Field As String
        
        Private institucion2Field As String
        
        Private institucion3Field As String
        
        Private numeroCuenta1Field As String
        
        Private numeroCuenta2Field As String
        
        Private numeroCuenta3Field As String
        
        Private limiteCuenta1Field As Decimal
        
        Private limiteCuenta2Field As Decimal
        
        Private limiteCuenta3Field As Decimal
        
        '''<comentarios/>
        Public Property CreditoDPValeID() As Integer
            Get
                Return Me.creditoDPValeIDField
            End Get
            Set
                Me.creditoDPValeIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AsociadoID() As Integer
            Get
                Return Me.asociadoIDField
            End Get
            Set
                Me.asociadoIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ClienteID() As Integer
            Get
                Return Me.clienteIDField
            End Get
            Set
                Me.clienteIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Banco() As String
            Get
                Return Me.bancoField
            End Get
            Set
                Me.bancoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property LimiteCreditoBancario() As Decimal
            Get
                Return Me.limiteCreditoBancarioField
            End Get
            Set
                Me.limiteCreditoBancarioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Plazo() As Integer
            Get
                Return Me.plazoField
            End Get
            Set
                Me.plazoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalNombre() As String
            Get
                Return Me.avalNombreField
            End Get
            Set
                Me.avalNombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalApellidoPaterno() As String
            Get
                Return Me.avalApellidoPaternoField
            End Get
            Set
                Me.avalApellidoPaternoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalApellidoMaterno() As String
            Get
                Return Me.avalApellidoMaternoField
            End Get
            Set
                Me.avalApellidoMaternoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalSexo() As String
            Get
                Return Me.avalSexoField
            End Get
            Set
                Me.avalSexoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalDomicilio() As String
            Get
                Return Me.avalDomicilioField
            End Get
            Set
                Me.avalDomicilioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalEstado() As String
            Get
                Return Me.avalEstadoField
            End Get
            Set
                Me.avalEstadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalCiudad() As String
            Get
                Return Me.avalCiudadField
            End Get
            Set
                Me.avalCiudadField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalColonia() As String
            Get
                Return Me.avalColoniaField
            End Get
            Set
                Me.avalColoniaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalTelefono() As String
            Get
                Return Me.avalTelefonoField
            End Get
            Set
                Me.avalTelefonoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalEmail() As String
            Get
                Return Me.avalEmailField
            End Get
            Set
                Me.avalEmailField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalCodigoPostal() As String
            Get
                Return Me.avalCodigoPostalField
            End Get
            Set
                Me.avalCodigoPostalField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaExpiracion() As Date
            Get
                Return Me.fechaExpiracionField
            End Get
            Set
                Me.fechaExpiracionField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property LimiteCredito() As Decimal
            Get
                Return Me.limiteCreditoField
            End Get
            Set
                Me.limiteCreditoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Saldo() As Decimal
            Get
                Return Me.saldoField
            End Get
            Set
                Me.saldoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SaldoVencido() As Decimal
            Get
                Return Me.saldoVencidoField
            End Get
            Set
                Me.saldoVencidoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CuentaContable() As String
            Get
                Return Me.cuentaContableField
            End Get
            Set
                Me.cuentaContableField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property FirmaDigital() As Byte()
            Get
                Return Me.firmaDigitalField
            End Get
            Set
                Me.firmaDigitalField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RecordCreatedBy() As String
            Get
                Return Me.recordCreatedByField
            End Get
            Set
                Me.recordCreatedByField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RecordCreatedOn() As Date
            Get
                Return Me.recordCreatedOnField
            End Get
            Set
                Me.recordCreatedOnField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RecordStatus() As Boolean
            Get
                Return Me.recordStatusField
            End Get
            Set
                Me.recordStatusField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Institucion1() As String
            Get
                Return Me.institucion1Field
            End Get
            Set
                Me.institucion1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Institucion2() As String
            Get
                Return Me.institucion2Field
            End Get
            Set
                Me.institucion2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Institucion3() As String
            Get
                Return Me.institucion3Field
            End Get
            Set
                Me.institucion3Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property NumeroCuenta1() As String
            Get
                Return Me.numeroCuenta1Field
            End Get
            Set
                Me.numeroCuenta1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property NumeroCuenta2() As String
            Get
                Return Me.numeroCuenta2Field
            End Get
            Set
                Me.numeroCuenta2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property NumeroCuenta3() As String
            Get
                Return Me.numeroCuenta3Field
            End Get
            Set
                Me.numeroCuenta3Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property LimiteCuenta1() As Decimal
            Get
                Return Me.limiteCuenta1Field
            End Get
            Set
                Me.limiteCuenta1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property LimiteCuenta2() As Decimal
            Get
                Return Me.limiteCuenta2Field
            End Get
            Set
                Me.limiteCuenta2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property LimiteCuenta3() As Decimal
            Get
                Return Me.limiteCuenta3Field
            End Get
            Set
                Me.limiteCuenta3Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub CreateCreditoDPValeCompletedEventHandler(ByVal sender As Object, ByVal e As CreateCreditoDPValeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateCreditoDPValeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub UpdateCreditoDPValeCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub UpdateCreditoDPValeSaldoCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DeleteCreditoDPValeCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetCreditoDPValeCompletedEventHandler(ByVal sender As Object, ByVal e As GetCreditoDPValeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCreditoDPValeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CreditoDPValeInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CreditoDPValeInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetListCreditosDPValeCompletedEventHandler(ByVal sender As Object, ByVal e As GetListCreditosDPValeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetListCreditosDPValeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetListCreditosDPValeByClienteCompletedEventHandler(ByVal sender As Object, ByVal e As GetListCreditosDPValeByClienteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetListCreditosDPValeByClienteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
