'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
'
Namespace wsCreditosEnTienda
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Credito .:::· CreditosEnTiendaSoap", [Namespace]:="http://ws.dportenis.com.mx/Credito/Creditos")>  _
    Partial Public Class CreditoCreditosEnTienda
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CreateCreditosEnTiendaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateCreditosEnTiendaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteCreditosEnTiendaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCreditosEnTiendaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCreditosEnTiendaByClienteIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetListCreditosEnTiendaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        ''' 
        Public strURL As String
        Public Sub New()
            MyBase.New
            'Me.Url = Global.DportenisPro.DPTienda.ApplicationUnits.Facturas.My.MySettings.Default.FacturasAU_wsCreditosEnTienda_Credito_x0020___x003A__x003A__x003A___x0020_CreditosEnTienda
            strURL = "credito/CreditosEnTienda.asmx"
            Dim urlSetting As String = System.Configuration.ConfigurationManager.AppSettings("FacturasFormaPagoAU.wsCreditosEnTienda.Credito .:::· CreditosEnTienda")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://dpssvr/credito/CreditosEnTienda.asmx"
            End If
            If (Me.IsLocalFileSystemWebService(Me.Url) = True) Then
                Me.UseDefaultCredentials = True
                Me.useDefaultCredentialsSetExplicitly = False
            Else
                Me.useDefaultCredentialsSetExplicitly = True
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CreateCreditosEnTiendaCompleted As CreateCreditosEnTiendaCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCreditosEnTiendaCompleted As UpdateCreditosEnTiendaCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteCreditosEnTiendaCompleted As DeleteCreditosEnTiendaCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCreditosEnTiendaCompleted As GetCreditosEnTiendaCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCreditosEnTiendaByClienteIDCompleted As GetCreditosEnTiendaByClienteIDCompletedEventHandler
        
        '''<remarks/>
        Public Event GetListCreditosEnTiendaCompleted As GetListCreditosEnTiendaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/Creditos/CreateCreditosEnTienda", RequestNamespace:="http://ws.dportenis.com.mx/Credito/Creditos", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/Creditos", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreateCreditosEnTienda(ByVal Data As CreditoEnTiendaInfo) As Integer
            Dim results() As Object = Me.Invoke("CreateCreditosEnTienda", New Object() {Data})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginCreateCreditosEnTienda(ByVal Data As CreditoEnTiendaInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreateCreditosEnTienda", New Object() {Data}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCreateCreditosEnTienda(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreateCreditosEnTiendaAsync(ByVal Data As CreditoEnTiendaInfo)
            Me.CreateCreditosEnTiendaAsync(Data, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateCreditosEnTiendaAsync(ByVal Data As CreditoEnTiendaInfo, ByVal userState As Object)
            If (Me.CreateCreditosEnTiendaOperationCompleted Is Nothing) Then
                Me.CreateCreditosEnTiendaOperationCompleted = AddressOf Me.OnCreateCreditosEnTiendaOperationCompleted
            End If
            Me.InvokeAsync("CreateCreditosEnTienda", New Object() {Data}, Me.CreateCreditosEnTiendaOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateCreditosEnTiendaOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateCreditosEnTiendaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateCreditosEnTiendaCompleted(Me, New CreateCreditosEnTiendaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/Creditos/UpdateCreditosEnTienda", RequestNamespace:="http://ws.dportenis.com.mx/Credito/Creditos", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/Creditos", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateCreditosEnTienda(ByVal Data As CreditoEnTiendaInfo)
            Me.Invoke("UpdateCreditosEnTienda", New Object() {Data})
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdateCreditosEnTienda(ByVal Data As CreditoEnTiendaInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateCreditosEnTienda", New Object() {Data}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdateCreditosEnTienda(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCreditosEnTiendaAsync(ByVal Data As CreditoEnTiendaInfo)
            Me.UpdateCreditosEnTiendaAsync(Data, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCreditosEnTiendaAsync(ByVal Data As CreditoEnTiendaInfo, ByVal userState As Object)
            If (Me.UpdateCreditosEnTiendaOperationCompleted Is Nothing) Then
                Me.UpdateCreditosEnTiendaOperationCompleted = AddressOf Me.OnUpdateCreditosEnTiendaOperationCompleted
            End If
            Me.InvokeAsync("UpdateCreditosEnTienda", New Object() {Data}, Me.UpdateCreditosEnTiendaOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateCreditosEnTiendaOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCreditosEnTiendaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCreditosEnTiendaCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/Creditos/DeleteCreditosEnTienda", RequestNamespace:="http://ws.dportenis.com.mx/Credito/Creditos", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/Creditos", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub DeleteCreditosEnTienda(ByVal ID As Integer)
            Me.Invoke("DeleteCreditosEnTienda", New Object() {ID})
        End Sub
        
        '''<remarks/>
        Public Function BeginDeleteCreditosEnTienda(ByVal ID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DeleteCreditosEnTienda", New Object() {ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndDeleteCreditosEnTienda(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteCreditosEnTiendaAsync(ByVal ID As Integer)
            Me.DeleteCreditosEnTiendaAsync(ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteCreditosEnTiendaAsync(ByVal ID As Integer, ByVal userState As Object)
            If (Me.DeleteCreditosEnTiendaOperationCompleted Is Nothing) Then
                Me.DeleteCreditosEnTiendaOperationCompleted = AddressOf Me.OnDeleteCreditosEnTiendaOperationCompleted
            End If
            Me.InvokeAsync("DeleteCreditosEnTienda", New Object() {ID}, Me.DeleteCreditosEnTiendaOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteCreditosEnTiendaOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteCreditosEnTiendaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteCreditosEnTiendaCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/Creditos/GetCreditosEnTienda", RequestNamespace:="http://ws.dportenis.com.mx/Credito/Creditos", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/Creditos", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCreditosEnTienda(ByVal ID As Integer) As CreditoEnTiendaInfo
            Dim results() As Object = Me.Invoke("GetCreditosEnTienda", New Object() {ID})
            Return CType(results(0),CreditoEnTiendaInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginGetCreditosEnTienda(ByVal ID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetCreditosEnTienda", New Object() {ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetCreditosEnTienda(ByVal asyncResult As System.IAsyncResult) As CreditoEnTiendaInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),CreditoEnTiendaInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCreditosEnTiendaAsync(ByVal ID As Integer)
            Me.GetCreditosEnTiendaAsync(ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCreditosEnTiendaAsync(ByVal ID As Integer, ByVal userState As Object)
            If (Me.GetCreditosEnTiendaOperationCompleted Is Nothing) Then
                Me.GetCreditosEnTiendaOperationCompleted = AddressOf Me.OnGetCreditosEnTiendaOperationCompleted
            End If
            Me.InvokeAsync("GetCreditosEnTienda", New Object() {ID}, Me.GetCreditosEnTiendaOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCreditosEnTiendaOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCreditosEnTiendaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCreditosEnTiendaCompleted(Me, New GetCreditosEnTiendaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/Creditos/GetCreditosEnTiendaByClienteID", RequestNamespace:="http://ws.dportenis.com.mx/Credito/Creditos", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/Creditos", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCreditosEnTiendaByClienteID(ByVal ID As Integer) As CreditoEnTiendaInfo
            Dim results() As Object = Me.Invoke("GetCreditosEnTiendaByClienteID", New Object() {ID})
            Return CType(results(0),CreditoEnTiendaInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginGetCreditosEnTiendaByClienteID(ByVal ID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetCreditosEnTiendaByClienteID", New Object() {ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetCreditosEnTiendaByClienteID(ByVal asyncResult As System.IAsyncResult) As CreditoEnTiendaInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),CreditoEnTiendaInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCreditosEnTiendaByClienteIDAsync(ByVal ID As Integer)
            Me.GetCreditosEnTiendaByClienteIDAsync(ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCreditosEnTiendaByClienteIDAsync(ByVal ID As Integer, ByVal userState As Object)
            If (Me.GetCreditosEnTiendaByClienteIDOperationCompleted Is Nothing) Then
                Me.GetCreditosEnTiendaByClienteIDOperationCompleted = AddressOf Me.OnGetCreditosEnTiendaByClienteIDOperationCompleted
            End If
            Me.InvokeAsync("GetCreditosEnTiendaByClienteID", New Object() {ID}, Me.GetCreditosEnTiendaByClienteIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCreditosEnTiendaByClienteIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCreditosEnTiendaByClienteIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCreditosEnTiendaByClienteIDCompleted(Me, New GetCreditosEnTiendaByClienteIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/Creditos/GetListCreditosEnTienda", RequestNamespace:="http://ws.dportenis.com.mx/Credito/Creditos", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/Creditos", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetListCreditosEnTienda(ByVal EnabledRecordsOnly As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetListCreditosEnTienda", New Object() {EnabledRecordsOnly})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetListCreditosEnTienda(ByVal EnabledRecordsOnly As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetListCreditosEnTienda", New Object() {EnabledRecordsOnly}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetListCreditosEnTienda(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetListCreditosEnTiendaAsync(ByVal EnabledRecordsOnly As Boolean)
            Me.GetListCreditosEnTiendaAsync(EnabledRecordsOnly, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetListCreditosEnTiendaAsync(ByVal EnabledRecordsOnly As Boolean, ByVal userState As Object)
            If (Me.GetListCreditosEnTiendaOperationCompleted Is Nothing) Then
                Me.GetListCreditosEnTiendaOperationCompleted = AddressOf Me.OnGetListCreditosEnTiendaOperationCompleted
            End If
            Me.InvokeAsync("GetListCreditosEnTienda", New Object() {EnabledRecordsOnly}, Me.GetListCreditosEnTiendaOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetListCreditosEnTiendaOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetListCreditosEnTiendaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetListCreditosEnTiendaCompleted(Me, New GetListCreditosEnTiendaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.dportenis.com.mx/Credito/Creditos")>  _
    Partial Public Class CreditoEnTiendaInfo
        
        Private creditoEnTiendaIDField As Integer
        
        Private asociadoIDField As Integer
        
        Private clienteIDField As Integer
        
        Private bancoField As String
        
        Private limiteCreditoBancarioField As Decimal
        
        Private plazoField As Integer
        
        Private avalNombreField As String
        
        Private avalApellidoPaternoField As String
        
        Private avalApellidoMaternoField As String
        
        Private avalSexoField As String
        
        Private avalDomicilioField As String
        
        Private avalEstadoField As String
        
        Private avalCiudadField As String
        
        Private avalColoniaField As String
        
        Private avalTelefonoField As String
        
        Private avalEmailField As String
        
        Private avalCodigoPostalField As String
        
        Private fechaExpiracionField As Date
        
        Private limiteCreditoField As Decimal
        
        Private saldoField As Decimal
        
        Private cuentaContableField As String
        
        Private firmaDigitalField() As Byte
        
        Private recordCreatedByField As String
        
        Private recordCreatedOnField As Date
        
        Private recordStatusField As Boolean
        
        Private saldoVencidoField As Decimal
        
        '''<comentarios/>
        Public Property CreditoEnTiendaID() As Integer
            Get
                Return Me.creditoEnTiendaIDField
            End Get
            Set
                Me.creditoEnTiendaIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AsociadoID() As Integer
            Get
                Return Me.asociadoIDField
            End Get
            Set
                Me.asociadoIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ClienteID() As Integer
            Get
                Return Me.clienteIDField
            End Get
            Set
                Me.clienteIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Banco() As String
            Get
                Return Me.bancoField
            End Get
            Set
                Me.bancoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property LimiteCreditoBancario() As Decimal
            Get
                Return Me.limiteCreditoBancarioField
            End Get
            Set
                Me.limiteCreditoBancarioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Plazo() As Integer
            Get
                Return Me.plazoField
            End Get
            Set
                Me.plazoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalNombre() As String
            Get
                Return Me.avalNombreField
            End Get
            Set
                Me.avalNombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalApellidoPaterno() As String
            Get
                Return Me.avalApellidoPaternoField
            End Get
            Set
                Me.avalApellidoPaternoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalApellidoMaterno() As String
            Get
                Return Me.avalApellidoMaternoField
            End Get
            Set
                Me.avalApellidoMaternoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalSexo() As String
            Get
                Return Me.avalSexoField
            End Get
            Set
                Me.avalSexoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalDomicilio() As String
            Get
                Return Me.avalDomicilioField
            End Get
            Set
                Me.avalDomicilioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalEstado() As String
            Get
                Return Me.avalEstadoField
            End Get
            Set
                Me.avalEstadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalCiudad() As String
            Get
                Return Me.avalCiudadField
            End Get
            Set
                Me.avalCiudadField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalColonia() As String
            Get
                Return Me.avalColoniaField
            End Get
            Set
                Me.avalColoniaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalTelefono() As String
            Get
                Return Me.avalTelefonoField
            End Get
            Set
                Me.avalTelefonoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalEmail() As String
            Get
                Return Me.avalEmailField
            End Get
            Set
                Me.avalEmailField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalCodigoPostal() As String
            Get
                Return Me.avalCodigoPostalField
            End Get
            Set
                Me.avalCodigoPostalField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaExpiracion() As Date
            Get
                Return Me.fechaExpiracionField
            End Get
            Set
                Me.fechaExpiracionField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property LimiteCredito() As Decimal
            Get
                Return Me.limiteCreditoField
            End Get
            Set
                Me.limiteCreditoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Saldo() As Decimal
            Get
                Return Me.saldoField
            End Get
            Set
                Me.saldoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CuentaContable() As String
            Get
                Return Me.cuentaContableField
            End Get
            Set
                Me.cuentaContableField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property FirmaDigital() As Byte()
            Get
                Return Me.firmaDigitalField
            End Get
            Set
                Me.firmaDigitalField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RecordCreatedBy() As String
            Get
                Return Me.recordCreatedByField
            End Get
            Set
                Me.recordCreatedByField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RecordCreatedOn() As Date
            Get
                Return Me.recordCreatedOnField
            End Get
            Set
                Me.recordCreatedOnField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RecordStatus() As Boolean
            Get
                Return Me.recordStatusField
            End Get
            Set
                Me.recordStatusField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SaldoVencido() As Decimal
            Get
                Return Me.saldoVencidoField
            End Get
            Set
                Me.saldoVencidoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub CreateCreditosEnTiendaCompletedEventHandler(ByVal sender As Object, ByVal e As CreateCreditosEnTiendaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateCreditosEnTiendaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub UpdateCreditosEnTiendaCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DeleteCreditosEnTiendaCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetCreditosEnTiendaCompletedEventHandler(ByVal sender As Object, ByVal e As GetCreditosEnTiendaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCreditosEnTiendaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CreditoEnTiendaInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CreditoEnTiendaInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetCreditosEnTiendaByClienteIDCompletedEventHandler(ByVal sender As Object, ByVal e As GetCreditosEnTiendaByClienteIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCreditosEnTiendaByClienteIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CreditoEnTiendaInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CreditoEnTiendaInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetListCreditosEnTiendaCompletedEventHandler(ByVal sender As Object, ByVal e As GetListCreditosEnTiendaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetListCreditosEnTiendaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
