'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
'
Namespace wsAbonosEnEfectivo
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AbonosCreditoEfectivoSoap", [Namespace]:="http://tempuri.org/Credito/AbonosCreditoEfectivo")>  _
    Partial Public Class AbonosCreditoEfectivo
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private AbonosEnEfectivoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.DportenisPro.DPTienda.ApplicationUnits.ArqueoDeCajaAU.My.MySettings.Default.ArqueoDeCajaAU_wsAbonosEnEfectivo_AbonosCreditoEfectivo
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event AbonosEnEfectivoCompleted As AbonosEnEfectivoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/AbonosCreditoEfectivo/AbonosEnEfectivo", RequestNamespace:="http://tempuri.org/Credito/AbonosCreditoEfectivo", ResponseNamespace:="http://tempuri.org/Credito/AbonosCreditoEfectivo", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AbonosEnEfectivo(ByVal Fecha As Date, ByVal Caja As String, ByVal CodAlmacen As String) As Decimal
            Dim results() As Object = Me.Invoke("AbonosEnEfectivo", New Object() {Fecha, Caja, CodAlmacen})
            Return CType(results(0),Decimal)
        End Function
        
        '''<remarks/>
        Public Function BeginAbonosEnEfectivo(ByVal Fecha As Date, ByVal Caja As String, ByVal CodAlmacen As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AbonosEnEfectivo", New Object() {Fecha, Caja, CodAlmacen}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndAbonosEnEfectivo(ByVal asyncResult As System.IAsyncResult) As Decimal
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Decimal)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AbonosEnEfectivoAsync(ByVal Fecha As Date, ByVal Caja As String, ByVal CodAlmacen As String)
            Me.AbonosEnEfectivoAsync(Fecha, Caja, CodAlmacen, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AbonosEnEfectivoAsync(ByVal Fecha As Date, ByVal Caja As String, ByVal CodAlmacen As String, ByVal userState As Object)
            If (Me.AbonosEnEfectivoOperationCompleted Is Nothing) Then
                Me.AbonosEnEfectivoOperationCompleted = AddressOf Me.OnAbonosEnEfectivoOperationCompleted
            End If
            Me.InvokeAsync("AbonosEnEfectivo", New Object() {Fecha, Caja, CodAlmacen}, Me.AbonosEnEfectivoOperationCompleted, userState)
        End Sub
        
        Private Sub OnAbonosEnEfectivoOperationCompleted(ByVal arg As Object)
            If (Not (Me.AbonosEnEfectivoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AbonosEnEfectivoCompleted(Me, New AbonosEnEfectivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub AbonosEnEfectivoCompletedEventHandler(ByVal sender As Object, ByVal e As AbonosEnEfectivoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AbonosEnEfectivoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Decimal
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Decimal)
            End Get
        End Property
    End Class
End Namespace
