'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
'
Namespace wsCreditoDPVale
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Credito .:::· CreditosDPValeSoap", [Namespace]:="http://ws.dportenis.com.mx/Credito/CreditosDPVale")>  _
    Partial Public Class CreditoCreditosDPVale
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CreateCreditoDPValeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateCreditoDPValeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateCreditoDPValeSaldoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateCreditoDPValeCongeladoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateCreditoDPValeRegistroZeroOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteCreditoDPValeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCreditoDPValeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetListCreditosDPValeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetListCreditosDPValeByClienteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetListCreditosDPValeByAsociadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetListCreditosDPValeZeroOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreditoDPValeSelAllToDocumentOperationCompleted As System.Threading.SendOrPostCallback
        
        Private BloquearCreditosDPValeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        ''' 
        Public strURL As String
        Public Sub New()
            MyBase.New
            'Me.Url = Global.DportenisPro.DPTienda.ApplicationUnits.FacturasFormaPago.My.MySettings.Default.FacturasFormaPagoAU_wsCreditoDPVale_Credito_x0020___x003A__x003A__x003A___x0020_CreditosDPVale
            strURL = "credito/CreditosDPVale.asmx"
            Dim urlSetting As String = System.Configuration.ConfigurationManager.AppSettings("FacturasFormaPagoAU.wsCreditoDPVale.Credito .:::· CreditosDPVale")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://dpssvr/credito/CreditosDPVale.asmx"
            End If
            If (Me.IsLocalFileSystemWebService(Me.Url) = True) Then
                Me.UseDefaultCredentials = True
                Me.useDefaultCredentialsSetExplicitly = False
            Else
                Me.useDefaultCredentialsSetExplicitly = True
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CreateCreditoDPValeCompleted As CreateCreditoDPValeCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCreditoDPValeCompleted As UpdateCreditoDPValeCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCreditoDPValeSaldoCompleted As UpdateCreditoDPValeSaldoCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCreditoDPValeCongeladoCompleted As UpdateCreditoDPValeCongeladoCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCreditoDPValeRegistroZeroCompleted As UpdateCreditoDPValeRegistroZeroCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteCreditoDPValeCompleted As DeleteCreditoDPValeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCreditoDPValeCompleted As GetCreditoDPValeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetListCreditosDPValeCompleted As GetListCreditosDPValeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetListCreditosDPValeByClienteCompleted As GetListCreditosDPValeByClienteCompletedEventHandler
        
        '''<remarks/>
        Public Event GetListCreditosDPValeByAsociadoCompleted As GetListCreditosDPValeByAsociadoCompletedEventHandler
        
        '''<remarks/>
        Public Event GetListCreditosDPValeZeroCompleted As GetListCreditosDPValeZeroCompletedEventHandler
        
        '''<remarks/>
        Public Event CreditoDPValeSelAllToDocumentCompleted As CreditoDPValeSelAllToDocumentCompletedEventHandler
        
        '''<remarks/>
        Public Event BloquearCreditosDPValeCompleted As BloquearCreditosDPValeCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/CreateCreditoDPVale", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreateCreditoDPVale(ByVal Data As CreditoDPValeInfo) As Integer
            Dim results() As Object = Me.Invoke("CreateCreditoDPVale", New Object() {Data})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginCreateCreditoDPVale(ByVal Data As CreditoDPValeInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreateCreditoDPVale", New Object() {Data}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCreateCreditoDPVale(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreateCreditoDPValeAsync(ByVal Data As CreditoDPValeInfo)
            Me.CreateCreditoDPValeAsync(Data, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateCreditoDPValeAsync(ByVal Data As CreditoDPValeInfo, ByVal userState As Object)
            If (Me.CreateCreditoDPValeOperationCompleted Is Nothing) Then
                Me.CreateCreditoDPValeOperationCompleted = AddressOf Me.OnCreateCreditoDPValeOperationCompleted
            End If
            Me.InvokeAsync("CreateCreditoDPVale", New Object() {Data}, Me.CreateCreditoDPValeOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateCreditoDPValeOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateCreditoDPValeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateCreditoDPValeCompleted(Me, New CreateCreditoDPValeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/UpdateCreditoDPVale", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateCreditoDPVale(ByVal Data As CreditoDPValeInfo)
            Me.Invoke("UpdateCreditoDPVale", New Object() {Data})
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdateCreditoDPVale(ByVal Data As CreditoDPValeInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateCreditoDPVale", New Object() {Data}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdateCreditoDPVale(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCreditoDPValeAsync(ByVal Data As CreditoDPValeInfo)
            Me.UpdateCreditoDPValeAsync(Data, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCreditoDPValeAsync(ByVal Data As CreditoDPValeInfo, ByVal userState As Object)
            If (Me.UpdateCreditoDPValeOperationCompleted Is Nothing) Then
                Me.UpdateCreditoDPValeOperationCompleted = AddressOf Me.OnUpdateCreditoDPValeOperationCompleted
            End If
            Me.InvokeAsync("UpdateCreditoDPVale", New Object() {Data}, Me.UpdateCreditoDPValeOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateCreditoDPValeOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCreditoDPValeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCreditoDPValeCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/UpdateCreditoDPValeSaldo", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateCreditoDPValeSaldo(ByVal AsociadoID As Integer, ByVal Monto As Decimal)
            Me.Invoke("UpdateCreditoDPValeSaldo", New Object() {AsociadoID, Monto})
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdateCreditoDPValeSaldo(ByVal AsociadoID As Integer, ByVal Monto As Decimal, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateCreditoDPValeSaldo", New Object() {AsociadoID, Monto}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdateCreditoDPValeSaldo(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCreditoDPValeSaldoAsync(ByVal AsociadoID As Integer, ByVal Monto As Decimal)
            Me.UpdateCreditoDPValeSaldoAsync(AsociadoID, Monto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCreditoDPValeSaldoAsync(ByVal AsociadoID As Integer, ByVal Monto As Decimal, ByVal userState As Object)
            If (Me.UpdateCreditoDPValeSaldoOperationCompleted Is Nothing) Then
                Me.UpdateCreditoDPValeSaldoOperationCompleted = AddressOf Me.OnUpdateCreditoDPValeSaldoOperationCompleted
            End If
            Me.InvokeAsync("UpdateCreditoDPValeSaldo", New Object() {AsociadoID, Monto}, Me.UpdateCreditoDPValeSaldoOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateCreditoDPValeSaldoOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCreditoDPValeSaldoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCreditoDPValeSaldoCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/UpdateCreditoDPValeCongelado", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateCreditoDPValeCongelado(ByVal CreditoDPValeID As Integer, ByVal Congelado As Boolean)
            Me.Invoke("UpdateCreditoDPValeCongelado", New Object() {CreditoDPValeID, Congelado})
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdateCreditoDPValeCongelado(ByVal CreditoDPValeID As Integer, ByVal Congelado As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateCreditoDPValeCongelado", New Object() {CreditoDPValeID, Congelado}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdateCreditoDPValeCongelado(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCreditoDPValeCongeladoAsync(ByVal CreditoDPValeID As Integer, ByVal Congelado As Boolean)
            Me.UpdateCreditoDPValeCongeladoAsync(CreditoDPValeID, Congelado, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCreditoDPValeCongeladoAsync(ByVal CreditoDPValeID As Integer, ByVal Congelado As Boolean, ByVal userState As Object)
            If (Me.UpdateCreditoDPValeCongeladoOperationCompleted Is Nothing) Then
                Me.UpdateCreditoDPValeCongeladoOperationCompleted = AddressOf Me.OnUpdateCreditoDPValeCongeladoOperationCompleted
            End If
            Me.InvokeAsync("UpdateCreditoDPValeCongelado", New Object() {CreditoDPValeID, Congelado}, Me.UpdateCreditoDPValeCongeladoOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateCreditoDPValeCongeladoOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCreditoDPValeCongeladoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCreditoDPValeCongeladoCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/UpdateCreditoDPValeRegistroZero"& _ 
            "", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateCreditoDPValeRegistroZero(ByVal CreditoDPValeID As Integer)
            Me.Invoke("UpdateCreditoDPValeRegistroZero", New Object() {CreditoDPValeID})
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdateCreditoDPValeRegistroZero(ByVal CreditoDPValeID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateCreditoDPValeRegistroZero", New Object() {CreditoDPValeID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdateCreditoDPValeRegistroZero(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCreditoDPValeRegistroZeroAsync(ByVal CreditoDPValeID As Integer)
            Me.UpdateCreditoDPValeRegistroZeroAsync(CreditoDPValeID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateCreditoDPValeRegistroZeroAsync(ByVal CreditoDPValeID As Integer, ByVal userState As Object)
            If (Me.UpdateCreditoDPValeRegistroZeroOperationCompleted Is Nothing) Then
                Me.UpdateCreditoDPValeRegistroZeroOperationCompleted = AddressOf Me.OnUpdateCreditoDPValeRegistroZeroOperationCompleted
            End If
            Me.InvokeAsync("UpdateCreditoDPValeRegistroZero", New Object() {CreditoDPValeID}, Me.UpdateCreditoDPValeRegistroZeroOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateCreditoDPValeRegistroZeroOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCreditoDPValeRegistroZeroCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCreditoDPValeRegistroZeroCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/DeleteCreditoDPVale", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub DeleteCreditoDPVale(ByVal ID As Integer)
            Me.Invoke("DeleteCreditoDPVale", New Object() {ID})
        End Sub
        
        '''<remarks/>
        Public Function BeginDeleteCreditoDPVale(ByVal ID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DeleteCreditoDPVale", New Object() {ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndDeleteCreditoDPVale(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteCreditoDPValeAsync(ByVal ID As Integer)
            Me.DeleteCreditoDPValeAsync(ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteCreditoDPValeAsync(ByVal ID As Integer, ByVal userState As Object)
            If (Me.DeleteCreditoDPValeOperationCompleted Is Nothing) Then
                Me.DeleteCreditoDPValeOperationCompleted = AddressOf Me.OnDeleteCreditoDPValeOperationCompleted
            End If
            Me.InvokeAsync("DeleteCreditoDPVale", New Object() {ID}, Me.DeleteCreditoDPValeOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteCreditoDPValeOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteCreditoDPValeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteCreditoDPValeCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/GetCreditoDPVale", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCreditoDPVale(ByVal ID As Integer) As CreditoDPValeInfo
            Dim results() As Object = Me.Invoke("GetCreditoDPVale", New Object() {ID})
            Return CType(results(0),CreditoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginGetCreditoDPVale(ByVal ID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetCreditoDPVale", New Object() {ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetCreditoDPVale(ByVal asyncResult As System.IAsyncResult) As CreditoDPValeInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),CreditoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCreditoDPValeAsync(ByVal ID As Integer)
            Me.GetCreditoDPValeAsync(ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCreditoDPValeAsync(ByVal ID As Integer, ByVal userState As Object)
            If (Me.GetCreditoDPValeOperationCompleted Is Nothing) Then
                Me.GetCreditoDPValeOperationCompleted = AddressOf Me.OnGetCreditoDPValeOperationCompleted
            End If
            Me.InvokeAsync("GetCreditoDPVale", New Object() {ID}, Me.GetCreditoDPValeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCreditoDPValeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCreditoDPValeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCreditoDPValeCompleted(Me, New GetCreditoDPValeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/GetListCreditosDPVale", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetListCreditosDPVale(ByVal EnabledRecordsOnly As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetListCreditosDPVale", New Object() {EnabledRecordsOnly})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetListCreditosDPVale(ByVal EnabledRecordsOnly As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetListCreditosDPVale", New Object() {EnabledRecordsOnly}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetListCreditosDPVale(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetListCreditosDPValeAsync(ByVal EnabledRecordsOnly As Boolean)
            Me.GetListCreditosDPValeAsync(EnabledRecordsOnly, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetListCreditosDPValeAsync(ByVal EnabledRecordsOnly As Boolean, ByVal userState As Object)
            If (Me.GetListCreditosDPValeOperationCompleted Is Nothing) Then
                Me.GetListCreditosDPValeOperationCompleted = AddressOf Me.OnGetListCreditosDPValeOperationCompleted
            End If
            Me.InvokeAsync("GetListCreditosDPVale", New Object() {EnabledRecordsOnly}, Me.GetListCreditosDPValeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetListCreditosDPValeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetListCreditosDPValeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetListCreditosDPValeCompleted(Me, New GetListCreditosDPValeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/GetListCreditosDPValeByCliente", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetListCreditosDPValeByCliente(ByVal PlazaID As String, ByVal EnabledRecordsOnly As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetListCreditosDPValeByCliente", New Object() {PlazaID, EnabledRecordsOnly})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetListCreditosDPValeByCliente(ByVal PlazaID As String, ByVal EnabledRecordsOnly As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetListCreditosDPValeByCliente", New Object() {PlazaID, EnabledRecordsOnly}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetListCreditosDPValeByCliente(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetListCreditosDPValeByClienteAsync(ByVal PlazaID As String, ByVal EnabledRecordsOnly As Boolean)
            Me.GetListCreditosDPValeByClienteAsync(PlazaID, EnabledRecordsOnly, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetListCreditosDPValeByClienteAsync(ByVal PlazaID As String, ByVal EnabledRecordsOnly As Boolean, ByVal userState As Object)
            If (Me.GetListCreditosDPValeByClienteOperationCompleted Is Nothing) Then
                Me.GetListCreditosDPValeByClienteOperationCompleted = AddressOf Me.OnGetListCreditosDPValeByClienteOperationCompleted
            End If
            Me.InvokeAsync("GetListCreditosDPValeByCliente", New Object() {PlazaID, EnabledRecordsOnly}, Me.GetListCreditosDPValeByClienteOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetListCreditosDPValeByClienteOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetListCreditosDPValeByClienteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetListCreditosDPValeByClienteCompleted(Me, New GetListCreditosDPValeByClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/GetListCreditosDPValeByAsociado"& _ 
            "", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetListCreditosDPValeByAsociado(ByVal AsociadoID As Integer) As CreditoDPValeInfo
            Dim results() As Object = Me.Invoke("GetListCreditosDPValeByAsociado", New Object() {AsociadoID})
            Return CType(results(0),CreditoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginGetListCreditosDPValeByAsociado(ByVal AsociadoID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetListCreditosDPValeByAsociado", New Object() {AsociadoID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetListCreditosDPValeByAsociado(ByVal asyncResult As System.IAsyncResult) As CreditoDPValeInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),CreditoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetListCreditosDPValeByAsociadoAsync(ByVal AsociadoID As Integer)
            Me.GetListCreditosDPValeByAsociadoAsync(AsociadoID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetListCreditosDPValeByAsociadoAsync(ByVal AsociadoID As Integer, ByVal userState As Object)
            If (Me.GetListCreditosDPValeByAsociadoOperationCompleted Is Nothing) Then
                Me.GetListCreditosDPValeByAsociadoOperationCompleted = AddressOf Me.OnGetListCreditosDPValeByAsociadoOperationCompleted
            End If
            Me.InvokeAsync("GetListCreditosDPValeByAsociado", New Object() {AsociadoID}, Me.GetListCreditosDPValeByAsociadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetListCreditosDPValeByAsociadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetListCreditosDPValeByAsociadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetListCreditosDPValeByAsociadoCompleted(Me, New GetListCreditosDPValeByAsociadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/GetListCreditosDPValeZero", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetListCreditosDPValeZero() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetListCreditosDPValeZero", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetListCreditosDPValeZero(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetListCreditosDPValeZero", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetListCreditosDPValeZero(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetListCreditosDPValeZeroAsync()
            Me.GetListCreditosDPValeZeroAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetListCreditosDPValeZeroAsync(ByVal userState As Object)
            If (Me.GetListCreditosDPValeZeroOperationCompleted Is Nothing) Then
                Me.GetListCreditosDPValeZeroOperationCompleted = AddressOf Me.OnGetListCreditosDPValeZeroOperationCompleted
            End If
            Me.InvokeAsync("GetListCreditosDPValeZero", New Object(-1) {}, Me.GetListCreditosDPValeZeroOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetListCreditosDPValeZeroOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetListCreditosDPValeZeroCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetListCreditosDPValeZeroCompleted(Me, New GetListCreditosDPValeZeroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/CreditoDPValeSelAllToDocument", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreditoDPValeSelAllToDocument(ByVal Plaza As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("CreditoDPValeSelAllToDocument", New Object() {Plaza})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginCreditoDPValeSelAllToDocument(ByVal Plaza As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CreditoDPValeSelAllToDocument", New Object() {Plaza}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCreditoDPValeSelAllToDocument(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreditoDPValeSelAllToDocumentAsync(ByVal Plaza As String)
            Me.CreditoDPValeSelAllToDocumentAsync(Plaza, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreditoDPValeSelAllToDocumentAsync(ByVal Plaza As String, ByVal userState As Object)
            If (Me.CreditoDPValeSelAllToDocumentOperationCompleted Is Nothing) Then
                Me.CreditoDPValeSelAllToDocumentOperationCompleted = AddressOf Me.OnCreditoDPValeSelAllToDocumentOperationCompleted
            End If
            Me.InvokeAsync("CreditoDPValeSelAllToDocument", New Object() {Plaza}, Me.CreditoDPValeSelAllToDocumentOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreditoDPValeSelAllToDocumentOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreditoDPValeSelAllToDocumentCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreditoDPValeSelAllToDocumentCompleted(Me, New CreditoDPValeSelAllToDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.dportenis.com.mx/Credito/CreditosDPVale/BloquearCreditosDPVale", RequestNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", ResponseNamespace:="http://ws.dportenis.com.mx/Credito/CreditosDPVale", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub BloquearCreditosDPVale(ByVal Folios As String, ByVal Status As Boolean)
            Me.Invoke("BloquearCreditosDPVale", New Object() {Folios, Status})
        End Sub
        
        '''<remarks/>
        Public Function BeginBloquearCreditosDPVale(ByVal Folios As String, ByVal Status As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("BloquearCreditosDPVale", New Object() {Folios, Status}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndBloquearCreditosDPVale(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BloquearCreditosDPValeAsync(ByVal Folios As String, ByVal Status As Boolean)
            Me.BloquearCreditosDPValeAsync(Folios, Status, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub BloquearCreditosDPValeAsync(ByVal Folios As String, ByVal Status As Boolean, ByVal userState As Object)
            If (Me.BloquearCreditosDPValeOperationCompleted Is Nothing) Then
                Me.BloquearCreditosDPValeOperationCompleted = AddressOf Me.OnBloquearCreditosDPValeOperationCompleted
            End If
            Me.InvokeAsync("BloquearCreditosDPVale", New Object() {Folios, Status}, Me.BloquearCreditosDPValeOperationCompleted, userState)
        End Sub
        
        Private Sub OnBloquearCreditosDPValeOperationCompleted(ByVal arg As Object)
            If (Not (Me.BloquearCreditosDPValeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent BloquearCreditosDPValeCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.dportenis.com.mx/Credito/CreditosDPVale")>  _
    Partial Public Class CreditoDPValeInfo
        
        Private creditoDPValeIDField As Integer
        
        Private asociadoIDField As Integer
        
        Private clienteIDField As Integer
        
        Private avalNombreField As String
        
        Private avalApellidoPaternoField As String
        
        Private avalApellidoMaternoField As String
        
        Private avalSexoField As String
        
        Private avalDomicilioField As String
        
        Private avalEstadoField As String
        
        Private avalCiudadField As String
        
        Private avalColoniaField As String
        
        Private avalTelefonoField As String
        
        Private avalEmailField As String
        
        Private avalCodigoPostalField As String
        
        Private limiteCreditoField As Decimal
        
        Private saldoField As Decimal
        
        Private saldoVencidoField As Decimal
        
        Private firmaDigitalField() As Byte
        
        Private recordCreatedByField As String
        
        Private recordCreatedOnField As Date
        
        Private recordStatusField As Boolean
        
        Private institucion1Field As String
        
        Private institucion2Field As String
        
        Private institucion3Field As String
        
        Private numeroCuenta1Field As String
        
        Private numeroCuenta2Field As String
        
        Private numeroCuenta3Field As String
        
        Private limiteCuenta1Field As Decimal
        
        Private limiteCuenta2Field As Decimal
        
        Private limiteCuenta3Field As Decimal
        
        Private avalTelefonoOtroField As String
        
        Private observaciones1Field As String
        
        Private observaciones2Field As String
        
        Private observaciones3Field As String
        
        Private congeladoField As Boolean
        
        Private bloqueadoField As Boolean
        
        Private esEmpresaField As Boolean
        
        Private representanteField As RepresentanteCreditoInfo
        
        '''<comentarios/>
        Public Property CreditoDPValeID() As Integer
            Get
                Return Me.creditoDPValeIDField
            End Get
            Set
                Me.creditoDPValeIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AsociadoID() As Integer
            Get
                Return Me.asociadoIDField
            End Get
            Set
                Me.asociadoIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ClienteID() As Integer
            Get
                Return Me.clienteIDField
            End Get
            Set
                Me.clienteIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalNombre() As String
            Get
                Return Me.avalNombreField
            End Get
            Set
                Me.avalNombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalApellidoPaterno() As String
            Get
                Return Me.avalApellidoPaternoField
            End Get
            Set
                Me.avalApellidoPaternoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalApellidoMaterno() As String
            Get
                Return Me.avalApellidoMaternoField
            End Get
            Set
                Me.avalApellidoMaternoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalSexo() As String
            Get
                Return Me.avalSexoField
            End Get
            Set
                Me.avalSexoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalDomicilio() As String
            Get
                Return Me.avalDomicilioField
            End Get
            Set
                Me.avalDomicilioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalEstado() As String
            Get
                Return Me.avalEstadoField
            End Get
            Set
                Me.avalEstadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalCiudad() As String
            Get
                Return Me.avalCiudadField
            End Get
            Set
                Me.avalCiudadField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalColonia() As String
            Get
                Return Me.avalColoniaField
            End Get
            Set
                Me.avalColoniaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalTelefono() As String
            Get
                Return Me.avalTelefonoField
            End Get
            Set
                Me.avalTelefonoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalEmail() As String
            Get
                Return Me.avalEmailField
            End Get
            Set
                Me.avalEmailField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalCodigoPostal() As String
            Get
                Return Me.avalCodigoPostalField
            End Get
            Set
                Me.avalCodigoPostalField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property LimiteCredito() As Decimal
            Get
                Return Me.limiteCreditoField
            End Get
            Set
                Me.limiteCreditoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Saldo() As Decimal
            Get
                Return Me.saldoField
            End Get
            Set
                Me.saldoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SaldoVencido() As Decimal
            Get
                Return Me.saldoVencidoField
            End Get
            Set
                Me.saldoVencidoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property FirmaDigital() As Byte()
            Get
                Return Me.firmaDigitalField
            End Get
            Set
                Me.firmaDigitalField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RecordCreatedBy() As String
            Get
                Return Me.recordCreatedByField
            End Get
            Set
                Me.recordCreatedByField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RecordCreatedOn() As Date
            Get
                Return Me.recordCreatedOnField
            End Get
            Set
                Me.recordCreatedOnField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property RecordStatus() As Boolean
            Get
                Return Me.recordStatusField
            End Get
            Set
                Me.recordStatusField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Institucion1() As String
            Get
                Return Me.institucion1Field
            End Get
            Set
                Me.institucion1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Institucion2() As String
            Get
                Return Me.institucion2Field
            End Get
            Set
                Me.institucion2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Institucion3() As String
            Get
                Return Me.institucion3Field
            End Get
            Set
                Me.institucion3Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property NumeroCuenta1() As String
            Get
                Return Me.numeroCuenta1Field
            End Get
            Set
                Me.numeroCuenta1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property NumeroCuenta2() As String
            Get
                Return Me.numeroCuenta2Field
            End Get
            Set
                Me.numeroCuenta2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property NumeroCuenta3() As String
            Get
                Return Me.numeroCuenta3Field
            End Get
            Set
                Me.numeroCuenta3Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property LimiteCuenta1() As Decimal
            Get
                Return Me.limiteCuenta1Field
            End Get
            Set
                Me.limiteCuenta1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property LimiteCuenta2() As Decimal
            Get
                Return Me.limiteCuenta2Field
            End Get
            Set
                Me.limiteCuenta2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property LimiteCuenta3() As Decimal
            Get
                Return Me.limiteCuenta3Field
            End Get
            Set
                Me.limiteCuenta3Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AvalTelefonoOtro() As String
            Get
                Return Me.avalTelefonoOtroField
            End Get
            Set
                Me.avalTelefonoOtroField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Observaciones1() As String
            Get
                Return Me.observaciones1Field
            End Get
            Set
                Me.observaciones1Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Observaciones2() As String
            Get
                Return Me.observaciones2Field
            End Get
            Set
                Me.observaciones2Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Observaciones3() As String
            Get
                Return Me.observaciones3Field
            End Get
            Set
                Me.observaciones3Field = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Congelado() As Boolean
            Get
                Return Me.congeladoField
            End Get
            Set
                Me.congeladoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Bloqueado() As Boolean
            Get
                Return Me.bloqueadoField
            End Get
            Set
                Me.bloqueadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property EsEmpresa() As Boolean
            Get
                Return Me.esEmpresaField
            End Get
            Set
                Me.esEmpresaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Representante() As RepresentanteCreditoInfo
            Get
                Return Me.representanteField
            End Get
            Set
                Me.representanteField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.dportenis.com.mx/Credito/CreditosDPVale")>  _
    Partial Public Class RepresentanteCreditoInfo
        
        Private representanteCreditoIDField As Integer
        
        Private creditoDPValeIDField As Integer
        
        Private nombreField As String
        
        Private apellidoPaternoField As String
        
        Private apellidoMaternoField As String
        
        Private domicilioField As String
        
        Private coloniaField As String
        
        Private ciudadField As String
        
        Private estadoField As String
        
        Private eMailField As String
        
        Private cpField As String
        
        Private telefonoField As String
        
        Private sexoField As String
        
        Private telefonoOtroField As String
        
        Private firmaDigitalField() As Byte
        
        Private logotipoField() As Byte
        
        Private statusRegistroField As Boolean
        
        Private fechaField As Date
        
        Private usuarioField As String
        
        '''<comentarios/>
        Public Property RepresentanteCreditoID() As Integer
            Get
                Return Me.representanteCreditoIDField
            End Get
            Set
                Me.representanteCreditoIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CreditoDPValeID() As Integer
            Get
                Return Me.creditoDPValeIDField
            End Get
            Set
                Me.creditoDPValeIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ApellidoPaterno() As String
            Get
                Return Me.apellidoPaternoField
            End Get
            Set
                Me.apellidoPaternoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ApellidoMaterno() As String
            Get
                Return Me.apellidoMaternoField
            End Get
            Set
                Me.apellidoMaternoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Domicilio() As String
            Get
                Return Me.domicilioField
            End Get
            Set
                Me.domicilioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Colonia() As String
            Get
                Return Me.coloniaField
            End Get
            Set
                Me.coloniaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Ciudad() As String
            Get
                Return Me.ciudadField
            End Get
            Set
                Me.ciudadField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property EMail() As String
            Get
                Return Me.eMailField
            End Get
            Set
                Me.eMailField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CP() As String
            Get
                Return Me.cpField
            End Get
            Set
                Me.cpField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Telefono() As String
            Get
                Return Me.telefonoField
            End Get
            Set
                Me.telefonoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Sexo() As String
            Get
                Return Me.sexoField
            End Get
            Set
                Me.sexoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property TelefonoOtro() As String
            Get
                Return Me.telefonoOtroField
            End Get
            Set
                Me.telefonoOtroField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property FirmaDigital() As Byte()
            Get
                Return Me.firmaDigitalField
            End Get
            Set
                Me.firmaDigitalField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Logotipo() As Byte()
            Get
                Return Me.logotipoField
            End Get
            Set
                Me.logotipoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property StatusRegistro() As Boolean
            Get
                Return Me.statusRegistroField
            End Get
            Set
                Me.statusRegistroField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub CreateCreditoDPValeCompletedEventHandler(ByVal sender As Object, ByVal e As CreateCreditoDPValeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateCreditoDPValeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub UpdateCreditoDPValeCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub UpdateCreditoDPValeSaldoCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub UpdateCreditoDPValeCongeladoCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub UpdateCreditoDPValeRegistroZeroCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DeleteCreditoDPValeCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetCreditoDPValeCompletedEventHandler(ByVal sender As Object, ByVal e As GetCreditoDPValeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCreditoDPValeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CreditoDPValeInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CreditoDPValeInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetListCreditosDPValeCompletedEventHandler(ByVal sender As Object, ByVal e As GetListCreditosDPValeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetListCreditosDPValeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetListCreditosDPValeByClienteCompletedEventHandler(ByVal sender As Object, ByVal e As GetListCreditosDPValeByClienteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetListCreditosDPValeByClienteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetListCreditosDPValeByAsociadoCompletedEventHandler(ByVal sender As Object, ByVal e As GetListCreditosDPValeByAsociadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetListCreditosDPValeByAsociadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CreditoDPValeInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CreditoDPValeInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetListCreditosDPValeZeroCompletedEventHandler(ByVal sender As Object, ByVal e As GetListCreditosDPValeZeroCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetListCreditosDPValeZeroCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub CreditoDPValeSelAllToDocumentCompletedEventHandler(ByVal sender As Object, ByVal e As CreditoDPValeSelAllToDocumentCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreditoDPValeSelAllToDocumentCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub BloquearCreditosDPValeCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
