'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34209
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
'
Namespace wsAbonoCreditoDirecto
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AbonoCreditoDirectoXSoap", [Namespace]:="http://tempuri.org/Credito/AbonoCreditoDirecto")>  _
    Partial Public Class AbonoCreditoDirectoX
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private InsertAbonoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteAbonoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SelectCreditoDirectoAllOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SelectCreditoDirectoByIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SelectFacturasByIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SelectByDateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SelectAbonosFacturasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetUltimoAbonoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SelectAbonosCxCOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        ''' 
        Public strURL As String
        Public Sub New()
            MyBase.New
            'Me.Url = Global.DportenisPro.DPTienda.ApplicationUnits.AbonoCreditoDirectoTienda.My.MySettings.Default.AbonoCreditoDirectoTienda_wsAbonoCreditoDirecto_AbonoCreditoDirectoX
            strURL = "Credito/AbonoCreditoDirecto.asmx"
            Dim urlSetting As String = System.Configuration.ConfigurationManager.AppSettings("AbonoCreditoDirectoTienda.wsAbonoCreditoDirecto.AbonoCreditoDirectoX")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://localhost/Credito/AbonoCreditoDirecto.asmx"
            End If
            If (Me.IsLocalFileSystemWebService(Me.Url) = True) Then
                Me.UseDefaultCredentials = True
                Me.useDefaultCredentialsSetExplicitly = False
            Else
                Me.useDefaultCredentialsSetExplicitly = True
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event InsertAbonoCompleted As InsertAbonoCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteAbonoCompleted As DeleteAbonoCompletedEventHandler
        
        '''<remarks/>
        Public Event SelectCreditoDirectoAllCompleted As SelectCreditoDirectoAllCompletedEventHandler
        
        '''<remarks/>
        Public Event SelectCreditoDirectoByIDCompleted As SelectCreditoDirectoByIDCompletedEventHandler
        
        '''<remarks/>
        Public Event SelectFacturasByIDCompleted As SelectFacturasByIDCompletedEventHandler
        
        '''<remarks/>
        Public Event SelectByDateCompleted As SelectByDateCompletedEventHandler
        
        '''<remarks/>
        Public Event SelectAbonosFacturasCompleted As SelectAbonosFacturasCompletedEventHandler
        
        '''<remarks/>
        Public Event GetUltimoAbonoCompleted As GetUltimoAbonoCompletedEventHandler
        
        '''<remarks/>
        Public Event SelectAbonosCxCCompleted As SelectAbonosCxCCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/AbonoCreditoDirecto/InsertAbono", RequestNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", ResponseNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InsertAbono(ByVal oAbonoCreditoDirecto As AbonoCreditoDirectoInfo, ByVal oAbonoDPVale As AbonoDPValeInfo, ByVal IVA As Double) As AbonoDPValeInfo
            Dim results() As Object = Me.Invoke("InsertAbono", New Object() {oAbonoCreditoDirecto, oAbonoDPVale, IVA})
            Return CType(results(0),AbonoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginInsertAbono(ByVal oAbonoCreditoDirecto As AbonoCreditoDirectoInfo, ByVal oAbonoDPVale As AbonoDPValeInfo, ByVal IVA As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("InsertAbono", New Object() {oAbonoCreditoDirecto, oAbonoDPVale, IVA}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndInsertAbono(ByVal asyncResult As System.IAsyncResult) As AbonoDPValeInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AbonoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InsertAbonoAsync(ByVal oAbonoCreditoDirecto As AbonoCreditoDirectoInfo, ByVal oAbonoDPVale As AbonoDPValeInfo, ByVal IVA As Double)
            Me.InsertAbonoAsync(oAbonoCreditoDirecto, oAbonoDPVale, IVA, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InsertAbonoAsync(ByVal oAbonoCreditoDirecto As AbonoCreditoDirectoInfo, ByVal oAbonoDPVale As AbonoDPValeInfo, ByVal IVA As Double, ByVal userState As Object)
            If (Me.InsertAbonoOperationCompleted Is Nothing) Then
                Me.InsertAbonoOperationCompleted = AddressOf Me.OnInsertAbonoOperationCompleted
            End If
            Me.InvokeAsync("InsertAbono", New Object() {oAbonoCreditoDirecto, oAbonoDPVale, IVA}, Me.InsertAbonoOperationCompleted, userState)
        End Sub
        
        Private Sub OnInsertAbonoOperationCompleted(ByVal arg As Object)
            If (Not (Me.InsertAbonoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InsertAbonoCompleted(Me, New InsertAbonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/AbonoCreditoDirecto/DeleteAbono", RequestNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", ResponseNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub DeleteAbono(ByVal oAbonoCreditoDirecto As AbonoCreditoDirectoInfo, ByVal oAbonoDPVale As AbonoDPValeInfo)
            Me.Invoke("DeleteAbono", New Object() {oAbonoCreditoDirecto, oAbonoDPVale})
        End Sub
        
        '''<remarks/>
        Public Function BeginDeleteAbono(ByVal oAbonoCreditoDirecto As AbonoCreditoDirectoInfo, ByVal oAbonoDPVale As AbonoDPValeInfo, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DeleteAbono", New Object() {oAbonoCreditoDirecto, oAbonoDPVale}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndDeleteAbono(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteAbonoAsync(ByVal oAbonoCreditoDirecto As AbonoCreditoDirectoInfo, ByVal oAbonoDPVale As AbonoDPValeInfo)
            Me.DeleteAbonoAsync(oAbonoCreditoDirecto, oAbonoDPVale, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteAbonoAsync(ByVal oAbonoCreditoDirecto As AbonoCreditoDirectoInfo, ByVal oAbonoDPVale As AbonoDPValeInfo, ByVal userState As Object)
            If (Me.DeleteAbonoOperationCompleted Is Nothing) Then
                Me.DeleteAbonoOperationCompleted = AddressOf Me.OnDeleteAbonoOperationCompleted
            End If
            Me.InvokeAsync("DeleteAbono", New Object() {oAbonoCreditoDirecto, oAbonoDPVale}, Me.DeleteAbonoOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteAbonoOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteAbonoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteAbonoCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/AbonoCreditoDirecto/SelectCreditoDirectoAll", RequestNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", ResponseNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SelectCreditoDirectoAll(ByVal OnlyEnabledRecords As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SelectCreditoDirectoAll", New Object() {OnlyEnabledRecords})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginSelectCreditoDirectoAll(ByVal OnlyEnabledRecords As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SelectCreditoDirectoAll", New Object() {OnlyEnabledRecords}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSelectCreditoDirectoAll(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SelectCreditoDirectoAllAsync(ByVal OnlyEnabledRecords As Boolean)
            Me.SelectCreditoDirectoAllAsync(OnlyEnabledRecords, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SelectCreditoDirectoAllAsync(ByVal OnlyEnabledRecords As Boolean, ByVal userState As Object)
            If (Me.SelectCreditoDirectoAllOperationCompleted Is Nothing) Then
                Me.SelectCreditoDirectoAllOperationCompleted = AddressOf Me.OnSelectCreditoDirectoAllOperationCompleted
            End If
            Me.InvokeAsync("SelectCreditoDirectoAll", New Object() {OnlyEnabledRecords}, Me.SelectCreditoDirectoAllOperationCompleted, userState)
        End Sub
        
        Private Sub OnSelectCreditoDirectoAllOperationCompleted(ByVal arg As Object)
            If (Not (Me.SelectCreditoDirectoAllCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SelectCreditoDirectoAllCompleted(Me, New SelectCreditoDirectoAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/AbonoCreditoDirecto/SelectCreditoDirectoByID", RequestNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", ResponseNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SelectCreditoDirectoByID(ByVal AsociadoID As Integer) As AbonoCreditoDirectoInfo
            Dim results() As Object = Me.Invoke("SelectCreditoDirectoByID", New Object() {AsociadoID})
            Return CType(results(0),AbonoCreditoDirectoInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginSelectCreditoDirectoByID(ByVal AsociadoID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SelectCreditoDirectoByID", New Object() {AsociadoID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSelectCreditoDirectoByID(ByVal asyncResult As System.IAsyncResult) As AbonoCreditoDirectoInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AbonoCreditoDirectoInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SelectCreditoDirectoByIDAsync(ByVal AsociadoID As Integer)
            Me.SelectCreditoDirectoByIDAsync(AsociadoID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SelectCreditoDirectoByIDAsync(ByVal AsociadoID As Integer, ByVal userState As Object)
            If (Me.SelectCreditoDirectoByIDOperationCompleted Is Nothing) Then
                Me.SelectCreditoDirectoByIDOperationCompleted = AddressOf Me.OnSelectCreditoDirectoByIDOperationCompleted
            End If
            Me.InvokeAsync("SelectCreditoDirectoByID", New Object() {AsociadoID}, Me.SelectCreditoDirectoByIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnSelectCreditoDirectoByIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.SelectCreditoDirectoByIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SelectCreditoDirectoByIDCompleted(Me, New SelectCreditoDirectoByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/AbonoCreditoDirecto/SelectFacturasByID", RequestNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", ResponseNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SelectFacturasByID(ByVal AsociadoID As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SelectFacturasByID", New Object() {AsociadoID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginSelectFacturasByID(ByVal AsociadoID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SelectFacturasByID", New Object() {AsociadoID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSelectFacturasByID(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SelectFacturasByIDAsync(ByVal AsociadoID As Integer)
            Me.SelectFacturasByIDAsync(AsociadoID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SelectFacturasByIDAsync(ByVal AsociadoID As Integer, ByVal userState As Object)
            If (Me.SelectFacturasByIDOperationCompleted Is Nothing) Then
                Me.SelectFacturasByIDOperationCompleted = AddressOf Me.OnSelectFacturasByIDOperationCompleted
            End If
            Me.InvokeAsync("SelectFacturasByID", New Object() {AsociadoID}, Me.SelectFacturasByIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnSelectFacturasByIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.SelectFacturasByIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SelectFacturasByIDCompleted(Me, New SelectFacturasByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/AbonoCreditoDirecto/SelectByDate", RequestNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", ResponseNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SelectByDate(ByVal Fecha As Date, ByVal Almacen As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SelectByDate", New Object() {Fecha, Almacen})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginSelectByDate(ByVal Fecha As Date, ByVal Almacen As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SelectByDate", New Object() {Fecha, Almacen}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSelectByDate(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SelectByDateAsync(ByVal Fecha As Date, ByVal Almacen As String)
            Me.SelectByDateAsync(Fecha, Almacen, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SelectByDateAsync(ByVal Fecha As Date, ByVal Almacen As String, ByVal userState As Object)
            If (Me.SelectByDateOperationCompleted Is Nothing) Then
                Me.SelectByDateOperationCompleted = AddressOf Me.OnSelectByDateOperationCompleted
            End If
            Me.InvokeAsync("SelectByDate", New Object() {Fecha, Almacen}, Me.SelectByDateOperationCompleted, userState)
        End Sub
        
        Private Sub OnSelectByDateOperationCompleted(ByVal arg As Object)
            If (Not (Me.SelectByDateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SelectByDateCompleted(Me, New SelectByDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/AbonoCreditoDirecto/SelectAbonosFacturas", RequestNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", ResponseNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SelectAbonosFacturas(ByVal AbonoID As Integer, ByVal CodAlmacen As String, ByVal CodCaja As String, ByVal Fecha As Date) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SelectAbonosFacturas", New Object() {AbonoID, CodAlmacen, CodCaja, Fecha})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginSelectAbonosFacturas(ByVal AbonoID As Integer, ByVal CodAlmacen As String, ByVal CodCaja As String, ByVal Fecha As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SelectAbonosFacturas", New Object() {AbonoID, CodAlmacen, CodCaja, Fecha}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSelectAbonosFacturas(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SelectAbonosFacturasAsync(ByVal AbonoID As Integer, ByVal CodAlmacen As String, ByVal CodCaja As String, ByVal Fecha As Date)
            Me.SelectAbonosFacturasAsync(AbonoID, CodAlmacen, CodCaja, Fecha, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SelectAbonosFacturasAsync(ByVal AbonoID As Integer, ByVal CodAlmacen As String, ByVal CodCaja As String, ByVal Fecha As Date, ByVal userState As Object)
            If (Me.SelectAbonosFacturasOperationCompleted Is Nothing) Then
                Me.SelectAbonosFacturasOperationCompleted = AddressOf Me.OnSelectAbonosFacturasOperationCompleted
            End If
            Me.InvokeAsync("SelectAbonosFacturas", New Object() {AbonoID, CodAlmacen, CodCaja, Fecha}, Me.SelectAbonosFacturasOperationCompleted, userState)
        End Sub
        
        Private Sub OnSelectAbonosFacturasOperationCompleted(ByVal arg As Object)
            If (Not (Me.SelectAbonosFacturasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SelectAbonosFacturasCompleted(Me, New SelectAbonosFacturasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/AbonoCreditoDirecto/GetUltimoAbono", RequestNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", ResponseNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUltimoAbono(ByVal CodSegmentoCredito As String, ByVal AsociadoId As Integer) As AbonoDPValeInfo
            Dim results() As Object = Me.Invoke("GetUltimoAbono", New Object() {CodSegmentoCredito, AsociadoId})
            Return CType(results(0),AbonoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Function BeginGetUltimoAbono(ByVal CodSegmentoCredito As String, ByVal AsociadoId As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetUltimoAbono", New Object() {CodSegmentoCredito, AsociadoId}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetUltimoAbono(ByVal asyncResult As System.IAsyncResult) As AbonoDPValeInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AbonoDPValeInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUltimoAbonoAsync(ByVal CodSegmentoCredito As String, ByVal AsociadoId As Integer)
            Me.GetUltimoAbonoAsync(CodSegmentoCredito, AsociadoId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUltimoAbonoAsync(ByVal CodSegmentoCredito As String, ByVal AsociadoId As Integer, ByVal userState As Object)
            If (Me.GetUltimoAbonoOperationCompleted Is Nothing) Then
                Me.GetUltimoAbonoOperationCompleted = AddressOf Me.OnGetUltimoAbonoOperationCompleted
            End If
            Me.InvokeAsync("GetUltimoAbono", New Object() {CodSegmentoCredito, AsociadoId}, Me.GetUltimoAbonoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUltimoAbonoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUltimoAbonoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUltimoAbonoCompleted(Me, New GetUltimoAbonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Credito/AbonoCreditoDirecto/SelectAbonosCxC", RequestNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", ResponseNamespace:="http://tempuri.org/Credito/AbonoCreditoDirecto", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SelectAbonosCxC(ByVal CodSegmentoCredito As String, ByVal Desde As Date, ByVal Hasta As Date, ByVal Almacen As String, ByVal Status As Boolean) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("SelectAbonosCxC", New Object() {CodSegmentoCredito, Desde, Hasta, Almacen, Status})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginSelectAbonosCxC(ByVal CodSegmentoCredito As String, ByVal Desde As Date, ByVal Hasta As Date, ByVal Almacen As String, ByVal Status As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SelectAbonosCxC", New Object() {CodSegmentoCredito, Desde, Hasta, Almacen, Status}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSelectAbonosCxC(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SelectAbonosCxCAsync(ByVal CodSegmentoCredito As String, ByVal Desde As Date, ByVal Hasta As Date, ByVal Almacen As String, ByVal Status As Boolean)
            Me.SelectAbonosCxCAsync(CodSegmentoCredito, Desde, Hasta, Almacen, Status, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SelectAbonosCxCAsync(ByVal CodSegmentoCredito As String, ByVal Desde As Date, ByVal Hasta As Date, ByVal Almacen As String, ByVal Status As Boolean, ByVal userState As Object)
            If (Me.SelectAbonosCxCOperationCompleted Is Nothing) Then
                Me.SelectAbonosCxCOperationCompleted = AddressOf Me.OnSelectAbonosCxCOperationCompleted
            End If
            Me.InvokeAsync("SelectAbonosCxC", New Object() {CodSegmentoCredito, Desde, Hasta, Almacen, Status}, Me.SelectAbonosCxCOperationCompleted, userState)
        End Sub
        
        Private Sub OnSelectAbonosCxCOperationCompleted(ByVal arg As Object)
            If (Not (Me.SelectAbonosCxCCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SelectAbonosCxCCompleted(Me, New SelectAbonosCxCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/Credito/AbonoCreditoDirecto")>  _
    Partial Public Class AbonoCreditoDirectoInfo
        
        Private creditoDirectoIDField As Integer
        
        Private asociadoIDField As Integer
        
        Private clienteIDField As Integer
        
        Private bancoField As String
        
        Private limCredBancoField As Double
        
        Private plazoField As Integer
        
        Private aNombreField As String
        
        Private aApellidoPaternoField As String
        
        Private aApellidoMaternoField As String
        
        Private aSexoField As Char
        
        Private aDomicilioField As String
        
        Private aEstadoField As String
        
        Private aCiudadField As String
        
        Private aColoniaField As String
        
        Private aTelefonoField As String
        
        Private aEMailField As String
        
        Private aCPField As Char
        
        Private fechaExpiracionField As Date
        
        Private limiteCreditoField As Double
        
        Private saldoField As Double
        
        Private saldoVencidoField As Double
        
        Private cuentaContableField As String
        
        Private firmaDigitalField As Byte
        
        Private usuarioField As String
        
        Private fechaField As Date
        
        Private statusRegistroField As Boolean
        
        Private facturasField As System.Data.DataSet
        
        Private formasDePagoField As System.Data.DataSet
        
        '''<comentarios/>
        Public Property CreditoDirectoID() As Integer
            Get
                Return Me.creditoDirectoIDField
            End Get
            Set
                Me.creditoDirectoIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AsociadoID() As Integer
            Get
                Return Me.asociadoIDField
            End Get
            Set
                Me.asociadoIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ClienteID() As Integer
            Get
                Return Me.clienteIDField
            End Get
            Set
                Me.clienteIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Banco() As String
            Get
                Return Me.bancoField
            End Get
            Set
                Me.bancoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property LimCredBanco() As Double
            Get
                Return Me.limCredBancoField
            End Get
            Set
                Me.limCredBancoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Plazo() As Integer
            Get
                Return Me.plazoField
            End Get
            Set
                Me.plazoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ANombre() As String
            Get
                Return Me.aNombreField
            End Get
            Set
                Me.aNombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AApellidoPaterno() As String
            Get
                Return Me.aApellidoPaternoField
            End Get
            Set
                Me.aApellidoPaternoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AApellidoMaterno() As String
            Get
                Return Me.aApellidoMaternoField
            End Get
            Set
                Me.aApellidoMaternoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ASexo() As Char
            Get
                Return Me.aSexoField
            End Get
            Set
                Me.aSexoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ADomicilio() As String
            Get
                Return Me.aDomicilioField
            End Get
            Set
                Me.aDomicilioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AEstado() As String
            Get
                Return Me.aEstadoField
            End Get
            Set
                Me.aEstadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ACiudad() As String
            Get
                Return Me.aCiudadField
            End Get
            Set
                Me.aCiudadField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AColonia() As String
            Get
                Return Me.aColoniaField
            End Get
            Set
                Me.aColoniaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ATelefono() As String
            Get
                Return Me.aTelefonoField
            End Get
            Set
                Me.aTelefonoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AEMail() As String
            Get
                Return Me.aEMailField
            End Get
            Set
                Me.aEMailField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property ACP() As Char
            Get
                Return Me.aCPField
            End Get
            Set
                Me.aCPField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FechaExpiracion() As Date
            Get
                Return Me.fechaExpiracionField
            End Get
            Set
                Me.fechaExpiracionField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property LimiteCredito() As Double
            Get
                Return Me.limiteCreditoField
            End Get
            Set
                Me.limiteCreditoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Saldo() As Double
            Get
                Return Me.saldoField
            End Get
            Set
                Me.saldoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SaldoVencido() As Double
            Get
                Return Me.saldoVencidoField
            End Get
            Set
                Me.saldoVencidoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CuentaContable() As String
            Get
                Return Me.cuentaContableField
            End Get
            Set
                Me.cuentaContableField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FirmaDigital() As Byte
            Get
                Return Me.firmaDigitalField
            End Get
            Set
                Me.firmaDigitalField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property StatusRegistro() As Boolean
            Get
                Return Me.statusRegistroField
            End Get
            Set
                Me.statusRegistroField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Facturas() As System.Data.DataSet
            Get
                Return Me.facturasField
            End Get
            Set
                Me.facturasField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property FormasDePago() As System.Data.DataSet
            Get
                Return Me.formasDePagoField
            End Get
            Set
                Me.formasDePagoField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/Credito/AbonoCreditoDirecto")>  _
    Partial Public Class AbonoDPValeInfo
        
        Private iDAbonoField As Integer
        
        Private codAlmacenField As String
        
        Private codCajaField As String
        
        Private iDClienteField As Integer
        
        Private codSegCredField As String
        
        Private codTipAbonoField As Integer
        
        Private saldoAntField As Double
        
        Private pagoMinField As Double
        
        Private montoPagoField As Double
        
        Private saldNuevoField As Double
        
        Private usuarioField As String
        
        Private fechaField As Date
        
        Private statusRegistroField As Boolean
        
        Private detalleField As System.Data.DataSet
        
        Private saldoDPValeField As Decimal
        
        Private asociadoIDField As Integer
        
        Private plazaConsecutivoField As String
        
        Private referenciaField As String
        
        Private bonificacionField As Double
        
        Private plazaField As String
        
        '''<comentarios/>
        Public Property IDAbono() As Integer
            Get
                Return Me.iDAbonoField
            End Get
            Set
                Me.iDAbonoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodAlmacen() As String
            Get
                Return Me.codAlmacenField
            End Get
            Set
                Me.codAlmacenField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodCaja() As String
            Get
                Return Me.codCajaField
            End Get
            Set
                Me.codCajaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property IDCliente() As Integer
            Get
                Return Me.iDClienteField
            End Get
            Set
                Me.iDClienteField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodSegCred() As String
            Get
                Return Me.codSegCredField
            End Get
            Set
                Me.codSegCredField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CodTipAbono() As Integer
            Get
                Return Me.codTipAbonoField
            End Get
            Set
                Me.codTipAbonoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SaldoAnt() As Double
            Get
                Return Me.saldoAntField
            End Get
            Set
                Me.saldoAntField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PagoMin() As Double
            Get
                Return Me.pagoMinField
            End Get
            Set
                Me.pagoMinField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property MontoPago() As Double
            Get
                Return Me.montoPagoField
            End Get
            Set
                Me.montoPagoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SaldNuevo() As Double
            Get
                Return Me.saldNuevoField
            End Get
            Set
                Me.saldNuevoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property StatusRegistro() As Boolean
            Get
                Return Me.statusRegistroField
            End Get
            Set
                Me.statusRegistroField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Detalle() As System.Data.DataSet
            Get
                Return Me.detalleField
            End Get
            Set
                Me.detalleField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SaldoDPVale() As Decimal
            Get
                Return Me.saldoDPValeField
            End Get
            Set
                Me.saldoDPValeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property AsociadoID() As Integer
            Get
                Return Me.asociadoIDField
            End Get
            Set
                Me.asociadoIDField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property PlazaConsecutivo() As String
            Get
                Return Me.plazaConsecutivoField
            End Get
            Set
                Me.plazaConsecutivoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Referencia() As String
            Get
                Return Me.referenciaField
            End Get
            Set
                Me.referenciaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Bonificacion() As Double
            Get
                Return Me.bonificacionField
            End Get
            Set
                Me.bonificacionField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Plaza() As String
            Get
                Return Me.plazaField
            End Get
            Set
                Me.plazaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub InsertAbonoCompletedEventHandler(ByVal sender As Object, ByVal e As InsertAbonoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InsertAbonoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AbonoDPValeInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AbonoDPValeInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub DeleteAbonoCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SelectCreditoDirectoAllCompletedEventHandler(ByVal sender As Object, ByVal e As SelectCreditoDirectoAllCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SelectCreditoDirectoAllCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SelectCreditoDirectoByIDCompletedEventHandler(ByVal sender As Object, ByVal e As SelectCreditoDirectoByIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SelectCreditoDirectoByIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AbonoCreditoDirectoInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AbonoCreditoDirectoInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SelectFacturasByIDCompletedEventHandler(ByVal sender As Object, ByVal e As SelectFacturasByIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SelectFacturasByIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SelectByDateCompletedEventHandler(ByVal sender As Object, ByVal e As SelectByDateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SelectByDateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SelectAbonosFacturasCompletedEventHandler(ByVal sender As Object, ByVal e As SelectAbonosFacturasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SelectAbonosFacturasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetUltimoAbonoCompletedEventHandler(ByVal sender As Object, ByVal e As GetUltimoAbonoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUltimoAbonoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AbonoDPValeInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AbonoDPValeInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SelectAbonosCxCCompletedEventHandler(ByVal sender As Object, ByVal e As SelectAbonosCxCCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SelectAbonosCxCCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
